<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Distribuciones Muestrales</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Didier Murillo</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Teaching.html">Teaching</a>
</li>
<li>
  <a href="about.html">About Me</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Distribuciones Muestrales</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#distribuciones-muestrales">Distribuciones Muestrales</a><ul>
<li><a href="#notacion">Notación</a></li>
<li><a href="#distribucion-de-la-media-muestral-cuando-la-poblacion-es-normal">Distribución de la media muestral cuando la población es normal</a></li>
<li><a href="#el-teorema-del-limite-central">El Teorema del Límite Central</a></li>
<li><a href="#aplicaciones">Aplicaciones:</a></li>
<li><a href="#distribucion-de-la-proporcion-muestral">Distribución de la Proporción Muestral</a></li>
</ul></li>
</ul>
</div>

<div id="distribuciones-muestrales" class="section level2">
<h2>Distribuciones Muestrales</h2>
<div id="uno-de-los-objetivos-de-la-estadistica-es-saber-acerca-del-comportamiento-de-parametros-poblacionales-tales-como-la-media-mu-la-varianza-sigma2-o-la-proporcion-p.-se-extrae-una-muestra-aleatoria-de-la-poblacion-y-se-calcula-el-valor-de-un-estadistico-correspondiente-por-ejemplo-la-media-muestral-barx-la-varianza-muestral-s2-o-la-proporcion-muestral-hatp.-el-valor-del-estadistico-es-aleatorio-porque-depende-de-los-elementos-elegidos-en-la-muestra-seleccionada-y-por-lo-tanto-el-estadistico-tiene-una-distribucion-de-probabilidad-la-cual-es-llamada-la-distribucion-muestral-del-estadistico." class="section level4">
<h4>Uno de los objetivos de la estadística es saber acerca del comportamiento de parámetros poblacionales tales como: la media <span class="math inline">\(\mu\)</span>, la varianza <span class="math inline">\(\sigma^2\)</span> o la proporción <span class="math inline">\(p\)</span>. Se extrae una muestra aleatoria de la población y se calcula el valor de un estadístico correspondiente, por ejemplo, la media muestral <span class="math inline">\(\bar{X}\)</span>, la varianza muestral <span class="math inline">\(S^2\)</span> o la proporción muestral <span class="math inline">\(\hat{p}\)</span>. El valor del estadístico es aleatorio porque depende de los elementos elegidos en la muestra seleccionada y, por lo tanto, el estadístico tiene una distribución de probabilidad la cual es llamada la <strong>Distribución Muestral del Estadístico</strong>.</h4>
</div>
<div id="notacion" class="section level3">
<h3>Notación</h3>
<div id="parametros" class="section level4">
<h4><strong>Parametros</strong>:</h4>
</div>
<div id="para-la-media-poblacional-se-usa-la-letra-mu." class="section level4">
<h4>Para la media poblacional se usa la letra <span class="math inline">\(\mu\)</span>.</h4>
</div>
<div id="para-la-varianza-poblacional-se-usa-la-letra-sigma2." class="section level4">
<h4>Para la varianza poblacional se usa la letra <span class="math inline">\(\sigma^2\)</span>.</h4>
</div>
<div id="para-la-varianza-poblacional-se-usa-la-letra-sigma." class="section level4">
<h4>Para la varianza poblacional se usa la letra <span class="math inline">\(\sigma\)</span>.</h4>
</div>
<div id="estadisticos" class="section level4">
<h4><strong>Estadísticos</strong>:</h4>
</div>
<div id="si-x-es-una-variable-aleatoria-entonces" class="section level4">
<h4>Si <span class="math inline">\(X\)</span> es una variable aleatoria, entonces:</h4>
</div>
<div id="para-la-media-muestral-se-usa-barx." class="section level4">
<h4>Para la media muestral se usa <span class="math inline">\(\bar{X}\)</span>.</h4>
</div>
<div id="para-la-varianza-muestral-se-usa-la-letra-s2." class="section level4">
<h4>Para la varianza muestral se usa la letra <span class="math inline">\(S^2\)</span>.</h4>
</div>
<div id="para-la-varianza-poblacional-se-usa-la-letra-s." class="section level4">
<h4>Para la varianza poblacional se usa la letra <span class="math inline">\(S\)</span>.</h4>
</div>
</div>
<div id="distribucion-de-la-media-muestral-cuando-la-poblacion-es-normal" class="section level3">
<h3>Distribución de la media muestral cuando la población es normal</h3>
<div id="suponga-que-su-objeto-de-estudio-es-una-poblacion-normal-y-de-donde-se-extraen-muestras-aleatorias-de-tamano-n-de-una-poblacion-infinita-con-media-poblacional-mu-y-varianza-sigma2.-entonces" class="section level4">
<h4>Suponga que su objeto de estudio es una población normal y de donde se extraen muestras aleatorias de tamaño <span class="math inline">\(n\)</span> de una población infinita con media poblacional <span class="math inline">\(\mu\)</span> y varianza <span class="math inline">\(\sigma^2\)</span>. Entonces,</h4>
<ul>
<li><h4 id="la-media-de-las-medias-muestrales-es-igual-a-la-media-poblacional.-es-decir">La media de las medias muestrales es igual a la media poblacional. Es decir,</h4></li>
</ul>
</div>
<div id="mu_barxmu" class="section level4">
<h4><span class="math display">\[\mu_{\bar{X}}=\mu\]</span></h4>
<ul>
<li><h4 id="la-varianza-de-las-medias-muestrales-es-igual-a-la-varianza-poblacional-dividida-por-n.-en-consecuencia-la-desviacion-estandar-de-las-medias-muestrales-llamada-tambien-el-error-estandar-de-la-media-muestral-es-igual-a-la-desviacion-estandar-poblacional-dividida-por-la-raiz-cuadrada-de-n.-es-decir">La varianza de las medias muestrales es igual a la varianza poblacional dividida por <span class="math inline">\(n\)</span>. En consecuencia la desviación estándar de las medias muestrales (llamada también el error estándar de la media muestral), es igual a la desviación estándar poblacional dividida por la raíz cuadrada de <span class="math inline">\(n\)</span>. Es decir,</h4></li>
</ul>
</div>
<div id="sigma_barxdfracsigmasqrtn" class="section level4">
<h4><span class="math display">\[\sigma_{\bar{X}}=\dfrac{\sigma}{\sqrt{n}}\]</span></h4>
<p>Finalmente se cumple que</p>
</div>
<div id="barx-sim-normalmufracsigmasqrtn" class="section level4">
<h4><span class="math display">\[\bar{X} \sim Normal(\mu,\frac{\sigma}{\sqrt{n}})\]</span></h4>
</div>
</div>
<div id="el-teorema-del-limite-central" class="section level3">
<h3>El Teorema del Límite Central</h3>
<div id="de-una-poblacion-con-media-y-varianza-se-extraen-muestras-aleatorias-de-tamano-n-entonces-la-media-muestral-barx-se-comporta-aproximadamente-como-una-variable-aleatoria-normal-con-media-igual-a-la-media-poblacional-mu-y-con-desviacion-estandar-sigma-igual-a-la-desviacion-poblacional-dividida-por-la-raiz-cuadrada-del-tamano-de-la-muestra-siempre-que-sea-grande.-esto-es" class="section level4">
<h4>De una población con media y varianza se extraen muestras aleatorias de tamaño <span class="math inline">\(n\)</span>, entonces la media muestral <span class="math inline">\(\bar{X}\)</span> se comporta aproximadamente como una variable aleatoria normal con media igual a la media poblacional <span class="math inline">\(\mu\)</span> y con desviación estándar <span class="math inline">\(\sigma\)</span> igual a la desviación poblacional dividida por la raíz cuadrada del tamaño de la muestra, siempre que sea grande. Esto es:</h4>
</div>
<div id="barx-sim-normalmufracsigmasqrtn-1" class="section level4">
<h4><span class="math display">\[\bar{X} \sim Normal(\mu,\frac{\sigma}{\sqrt{n}})\]</span></h4>
</div>
<div id="estandarizado-obtenemos" class="section level4">
<h4>Estandarizado, obtenemos:</h4>
</div>
<div id="z-dfracbarx-mudfracsigmasqrtn" class="section level4">
<h4><span class="math display">\[Z = \dfrac{\bar{X}-\mu}{\dfrac{\sigma}{\sqrt{n}}}\]</span></h4>
</div>
<div id="entonces" class="section level4">
<h4>entonces:</h4>
</div>
<div id="z-sim-normal01" class="section level4">
<h4><span class="math display">\[Z \sim Normal(0,1)\]</span></h4>
<blockquote>
<p>Ilustración de cómo funciona el Teorema del límite central</p>
</blockquote>
</div>
<div id="considerar-una-poblacion-que-consiste-de-los-siguientes-datos-3-4-6-8-10-11-12-15-17.-es-decir-n9." class="section level4">
<h4>Considerar una población que consiste de los siguientes datos: 3, 4, 6, 8, 10, 11, 12, 15, 17. Es decir N=9.</h4>
</div>
<div id="calculamos-la-media-y-desviacion-estandar-de-dicha-poblacion.-para-esto-usamos-rstudio" class="section level4">
<h4>1) Calculamos la media y desviación estándar de dicha población. Para esto usamos <code>RStudio</code></h4>
<pre class="r"><code>N &lt;- c(3, 4, 6, 8, 10, 11, 12, 15, 17)
media_N &lt;- mean(N)
media_N</code></pre>
<pre><code>## [1] 9.555556</code></pre>
<pre class="r"><code>sd_N &lt;- sd(N)
sd_N</code></pre>
<pre><code>## [1] 4.772607</code></pre>
</div>
<div id="notamos-que" class="section level4">
<h4>Notamos que,</h4>
</div>
<div id="mu9.55" class="section level4">
<h4><span class="math display">\[\mu=9.55\]</span></h4>
</div>
<div id="y-que" class="section level4">
<h4>y que</h4>
</div>
<div id="sigma4.77" class="section level4">
<h4><span class="math display">\[\sigma=4.77\]</span></h4>
</div>
<div id="extraemos-30-muestras-de-tamano-4-de-dicha-poblacion-esto-mediante-el-siguiente-codigo" class="section level4">
<h4>2) Extraemos 30 muestras de tamaño 4 de dicha población, esto mediante el siguiente código</h4>
<pre class="r"><code>N &lt;- c(3, 4, 6, 8, 10, 11, 12, 15, 17)
d_mean &lt;- c()
for (i in 1:30){
  d_mean[i] &lt;- mean(sample(N,size = 4,replace = TRUE))
}
print(d_mean)</code></pre>
<pre><code>##  [1]  7.50  8.75  6.75 13.50  8.00  9.00 11.50  9.75 11.50 10.75  6.25
## [12] 11.25 10.75 10.25  8.75 10.25 12.50 10.75 11.50  8.00  8.75 11.75
## [23] 12.25  8.75 10.25 12.25 10.00 14.75 11.75  5.75</code></pre>
</div>
<div id="calculamos-las-medias-de-todas-esas-muestras-y-tratamos-de-ver-graficamente-mediante-un-histograma-al-menos-si-hay-acercamiento-a-normalidad." class="section level4">
<h4>3) Calculamos las medias de todas esas muestras y tratamos de ver gráficamente mediante un histograma al menos si hay acercamiento a Normalidad.</h4>
<pre class="r"><code>mean(d_mean)</code></pre>
<pre><code>## [1] 10.11667</code></pre>
<pre class="r"><code>sd(d_mean)</code></pre>
<pre><code>## [1] 2.12815</code></pre>
<pre class="r"><code>hist(d_mean,col = &quot;cornflowerblue&quot;,freq = F,ylim = c(0,0.2))
curve(dnorm(x,mean(d_mean),sd(d_mean)),add=TRUE)</code></pre>
<p><img src="d_muestral_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="interpretacion" class="section level4">
<h4>Interpretación:</h4>
</div>
<div id="notar-que-la-media-de-las-medias-muestrales-es" class="section level4">
<h4>1. Notar que la media de las medias muestrales es</h4>
</div>
<div id="mu_barx-10.12." class="section level4">
<h4><span class="math inline">\(\mu_{\bar{X}}=\)</span> 10.12.</h4>
</div>
<div id="este-resultado-esta-bien-cerca-de-la-media-poblacional-pues-mu9.55" class="section level4">
<h4>Este resultado está bien cerca de la media poblacional, pues <span class="math inline">\(\mu=9.55\)</span></h4>
</div>
<div id="la-desviacion-estandar-de-la-media-muestral-es-2.13-mientras-que" class="section level4">
<h4>2. La desviación estándar de la media muestral es 2.13, mientras que</h4>
</div>
<div id="sigma_barxdfracsigmasqrtndfrac4.77sqrt42.4-." class="section level4">
<h4><span class="math inline">\(\sigma_{\bar{X}}=\dfrac{\sigma}{\sqrt{n}}=\dfrac{4.77}{\sqrt{4}}=2.4\)</span> .</h4>
</div>
<div id="notamos-que-ambos-valores-tambien-estan-relativamente-cerca." class="section level4">
<h4>Notamos que ambos valores también están relativamente cerca.</h4>
</div>
<div id="el-histograma-esta-un-poco-alejado-de-la-idea-de-normalidad." class="section level4">
<h4>El histograma está un poco alejado de la idea de Normalidad.</h4>
</div>
<div id="podemos-incrementar-el-tamano-de-las-muestras-se-puede-notar-una-mejor-aproximacion-a-la-normal." class="section level4">
<h4>Podemos incrementar el tamaño de las muestras se puede notar una mejor aproximación a la Normal.</h4>
</div>
<div id="si-se-incrementa-la-cantidad-de-muestras-a-diez-mil-se-puede-notar-graficamente-una-mejor-aproximacion-a-la-distribucion-normal-mediante-la-idea-del-histograma." class="section level4">
<h4>Si se incrementa la cantidad de muestras a diez mil, se puede notar gráficamente una mejor aproximación a la distribución Normal, mediante la idea del histograma.</h4>
<pre class="r"><code>N &lt;- c(3, 4, 6, 8, 10, 11, 12, 15, 17)
d_mean &lt;- c()
for (i in 1:10000){
  d_mean[i] &lt;- mean(sample(N,size = 4,replace = TRUE))
}
hist(d_mean,col = &quot;cornflowerblue&quot;,freq = F,ylim = c(0,0.2))
curve(dnorm(x,mean(d_mean),sd(d_mean)),add=TRUE)</code></pre>
<p><img src="d_muestral_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Ahora, con un mayor número de muestras tenemos que:</p>
</div>
<div id="mu_barx-9.52." class="section level4">
<h4><span class="math inline">\(\mu_{\bar{X}}=\)</span> 9.52.</h4>
</div>
<div id="este-resultado-esta-bien-cerca-de-la-media-poblacional-pues-mu9.55-1" class="section level4">
<h4>Este resultado está bien cerca de la media poblacional, pues <span class="math inline">\(\mu=9.55\)</span></h4>
</div>
<div id="la-desviacion-estandar-de-la-media-muestral-es-2.22-comparado-con-sigma_barx2.38" class="section level4">
<h4>2. La desviación estándar de la media muestral es 2.22, comparado con <span class="math inline">\(\sigma_{\bar{X}}=2.38\)</span></h4>
</div>
</div>
<div id="aplicaciones" class="section level3">
<h3>Aplicaciones:</h3>
<div id="caso-1-cuando-la-poblacion-es-normal." class="section level4">
<h4>Caso 1: Cuando la población es normal.</h4>
<ol style="list-style-type: decimal">
<li><h4 id="estadisticas-de-gpa.-el-promedio-de-calificaciones-de-todos-los-estudiantes-que-toman-cursos-de-introduccion-a-la-estadistica-en-los-estados-unidos-varia-segun-una-distribucion-normal-normal3-0.2">Estadísticas de GPA. El promedio de calificaciones de todos los estudiantes que toman cursos de introducción a la estadística en los Estados Unidos varía según una distribución normal <span class="math inline">\(Normal(3, 0.2)\)</span></h4></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><h4 id="cual-es-la-distribucion-muestral-del-promedio-muestral-para-una-clase-de-5-estudiantes">¿Cuál es la distribución muestral del promedio muestral para una clase de 5 estudiantes?</h4></li>
</ol>
</div>
<div id="supongamos-que-x-es-la-variable-aleatoria-entonces" class="section level4">
<h4>Supongamos que <span class="math inline">\(X\)</span> es la variable aleatoria, entonces</h4>
</div>
<div id="barx-sim-normalbig3frac0.2sqrt5big" class="section level4">
<h4><span class="math display">\[\bar{X} \sim Normal\Big(3,\frac{0.2}{\sqrt{5}}\Big)\]</span></h4>
<ol start="2" style="list-style-type: lower-alpha">
<li><h4 id="cual-es-la-distribucion-muestral-del-promedio-muestral-para-una-clase-de-40-estudiantes">¿Cuál es la distribución muestral del promedio muestral para una clase de 40 estudiantes?</h4></li>
</ol>
</div>
<div id="barx-sim-normalbig3frac0.2sqrt40big" class="section level4">
<h4><span class="math display">\[\bar{X} \sim Normal\Big(3,\frac{0.2}{\sqrt{40}}\Big)\]</span></h4>
<ol start="3" style="list-style-type: lower-alpha">
<li><h4 id="cual-es-la-distribucion-muestral-del-promedio-muestral-para-una-clase-de-100-estudiantes">¿Cuál es la distribución muestral del promedio muestral para una clase de 100 estudiantes?</h4></li>
</ol>
</div>
<div id="barx-sim-normalbig3frac0.2sqrt100big" class="section level4">
<h4><span class="math display">\[\bar{X} \sim Normal\Big(3,\frac{0.2}{\sqrt{100}}\Big)\]</span></h4>
<ol start="2" style="list-style-type: decimal">
<li><h4 id="se-extrae-un-muestra-de-tamano-n30-de-una-poblacion-que-tiene-una-distribucion-desconocida-con-media-mu-y-varianza-sigma2-pero-que-por-alguna-razon-conocemos-que-mu10y-que-sigma233.34.-con-la-informacion-anterior-estamos-interesados-en-contestar-las-siguientes-preguntas">Se extrae un muestra de tamaño <span class="math inline">\(n=30\)</span> de una población que tiene una distribución desconocida con media <span class="math inline">\(\mu\)</span> y varianza <span class="math inline">\(\sigma^2\)</span>, pero que por alguna razón conocemos que <span class="math inline">\(\mu=10\)</span>y que <span class="math inline">\(\sigma^2=33.34\)</span>. Con la información anterior estamos interesados en contestar las siguientes preguntas:</h4></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><h4 id="cual-es-la-distribucion-muestral-del-promedio-muestral-es-decir-la-distribucion-de-barx">¿Cuál es la distribución muestral del promedio muestral?, es decir la distribución de <span class="math inline">\(\bar{X}\)</span></h4></li>
<li><h4 id="cual-es-la-probabilidad-de-obtener-un-promedio-muestral-mayor-a-12.5">¿Cuál es la probabilidad de obtener un promedio muestral mayor a 12.5?</h4></li>
<li><h4 id="cual-es-la-probabilidad-de-encontrar-un-promedio-muestral-entre-8-y-15">¿Cuál es la probabilidad de encontrar un promedio muestral entre 8 y 15?</h4></li>
</ol>
</div>
<div id="caso-2-cuando-desconocemos-la-distribucion-de-la-poblacion-y-n-geq-30" class="section level4">
<h4>Caso 2: Cuando desconocemos la distribución de la población y <span class="math inline">\(n \geq 30\)</span></h4>
<ol style="list-style-type: decimal">
<li><h4 id="supongamos-que-el-ingreso-familiar-promedio-en-los-estados-unidos-es-de-51344-con-una-desviacion-estandar-de-15377.-cual-es-la-probabilidad-de-que-una-muestra-aleatoria-de-124-hogares-tenga-un-ingreso-familiar-promedio-de-mas-de-54000">Supongamos que el ingreso familiar promedio en los Estados Unidos es de <span class="math inline">\(\$51,344\)</span>, con una desviación estándar de <span class="math inline">\(\$15,377\)</span>. ¿Cuál es la probabilidad de que una muestra aleatoria de <span class="math inline">\(124\)</span> hogares tenga un ingreso familiar promedio de más de $ 54,000?</h4></li>
</ol>
</div>
</div>
<div id="distribucion-de-la-proporcion-muestral" class="section level3">
<h3>Distribución de la Proporción Muestral</h3>
<div id="si-de-una-poblacion-distribuida-binomialmente-con-probabilidad-de-exito-p-se-extrae-una-muestra-aleatoria-de-tamano-n-entonces-se-puede-mostrar-que-la-media-de-x-numero-de-exitos-en-la-muestra-es-munp-y-que-su-varianza-es-sigma2np1-p.-en-consecuencia-la-proporcion-muestral-hatpdfracxn-tiene-media-p-y-varianza-dfracp1-pn.-entonces-por-el-teorema-del-limite-central-cuando-n-es-grande-se-tiene" class="section level4">
<h4>Si de una población distribuida Binomialmente con probabilidad de éxito <span class="math inline">\(p\)</span>, se extrae una muestra aleatoria de tamaño <span class="math inline">\(n\)</span>, entonces se puede mostrar que la media de X: “número de éxitos en la muestra”, es <span class="math inline">\(\mu=np\)</span> y que su varianza es <span class="math inline">\(\sigma^2=np(1-p)\)</span>. En consecuencia la proporción muestral <span class="math inline">\(\hat{p}=\dfrac{X}{n}\)</span> tiene media <span class="math inline">\(p\)</span> y varianza <span class="math inline">\(\dfrac{p(1-p)}{n}\)</span>. Entonces: por el Teorema del Límite Central, cuando <span class="math inline">\(n\)</span> es grande se tiene:</h4>
</div>
<div id="zdfracx-npsqrtnp1-pdfrachatp-psqrtdfracp1-pn" class="section level4">
<h4><span class="math display">\[Z=\dfrac{X-np}{\sqrt{np(1-p)}}=\dfrac{\hat{p}-p}{\sqrt{\dfrac{p(1-p)}{n}}}\]</span></h4>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
