<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Estimación puntual y por intervalos</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Didier Murillo</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Teaching.html">Teaching</a>
</li>
<li>
  <a href="about.html">About Me</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Estimación puntual y por intervalos</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#estimacion-puntual-y-por-intervalos">Estimación puntual y por intervalos</a><ul>
<li><a href="#estimacion-puntual">Estimación puntual</a></li>
</ul></li>
<li><a href="#estimacion-por-intervalos">Estimación por intervalos</a><ul>
<li><a href="#intervalos-de-confianza-mas-precisos">Intervalos de confianza más precisos</a></li>
<li><a href="#intervalo-de-confianza-para-la-media-de-una-poblacion">Intervalo de confianza para la media de una población</a></li>
<li><a href="#intervalo-para-mu-con-sigma2-conocida">Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma^2\)</span> conocida</a></li>
<li><a href="#intervalo-para-mu-con-sigma2-desconocida">Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma^2\)</span> desconocida</a></li>
</ul></li>
<li><a href="#intervalo-de-confianza-para-proporciones">Intervalo de confianza para proporciones</a></li>
<li><a href="#ejercicios-de-repaso">Ejercicios de repaso</a></li>
</ul>
</div>

<div id="estimacion-puntual-y-por-intervalos" class="section level2">
<h2>Estimación puntual y por intervalos</h2>
<blockquote>
<p>¿Qué es un estimador?</p>
</blockquote>
<p>Cuando queremos realizar un estudio de una población cualquiera de la que desconocemos sus parámetros, debemos tomar una muestra aleatoria de dicha población a través de la cual se pueda calcular una aproximación a dichos parámetros que desconocemos y queremos estimar. Bien, pues esa aproximación se llama estimación. Además, junto a esa estimación, y dado que muy probablemente no coincida con el valor real del parámetro, acompañaremos el error aproximado que se comete al realizarla.</p>
<div id="estimacion-puntual" class="section level3">
<h3>Estimación puntual</h3>
<p>Una estimación puntual del valor de un parámetro poblacional desconocido (como puede ser la media <span class="math inline">\(\mu\)</span> , o la desviación estándar <span class="math inline">\(\sigma\)</span> ), es un número que se utiliza para aproximar el verdadero valor de dicho parámetro poblacional. A fin de realizar tal estimación, tomaremos una muestra aleatoria de la población y calcularemos el parámetro muestral asociado ( <span class="math inline">\(\bar{X}\)</span> para la media, <span class="math inline">\(s\)</span> para la desviación estándar, etc.). El valor de este parámetro muestral será la estimación puntual del parámetro poblacional.</p>
<p>Por ejemplo, supongamos que estamos interesados en estimar la edad media de los estudiantes subgraduados en el Colegio. Seleccionan una muestra de 100 estudiantes y calcula la media de esta muestra, este valor será un estimador puntual de la media de la población.</p>
<blockquote>
<p>¿Qué propiedades debe cumplir todo buen estimador?</p>
</blockquote>
<p><strong>Insesgado</strong>: Un estimador es insesgado cuando la media de su distribución muestral asociada coincide con la media de la población. Esto ocurre, por ejemplo, tomando el estadístico <span class="math inline">\(\bar{X}\)</span> como el estimador , ya que <span class="math inline">\(\mu_{\bar{x}}=\mu\)</span>.</p>
<blockquote>
<p>Ejemplos estimación puntual</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Queremos saber el porcentaje <span class="math inline">\(\pi\)</span> de los estudiantes en el Colegio a quienes les gusta la comida en la cafetería. Vamos a considerar a <span class="math inline">\(\pi\)</span> como el porcentaje para todos los estudiantes, es decir para toda la población, entonces <span class="math inline">\(\pi\)</span> es un parámetro desconocido.</li>
</ol>
<p>Para cada estudiante hay dos posibilidades: A él o ella le gusta la comida o no le gusta la comida. Entonces, si seleccionamos al azar a un estudiante, él / ella es un ensayo de Bernoulli. Si seleccionamos aleatoriamente n estudiantes, tenemos una muestra de n ensayos de Bernoulli. Sabemos que para un ensayo de Bernoulli con el parámetro <span class="math inline">\(\pi\)</span> la media poblacional <span class="math inline">\(\mu=\pi\)</span>.</p>
<p>Si hicimos un buen trabajo al seleccionar a los estudiantes para la muestra, entonces esperamos que la muestra signifique que <span class="math inline">\(\bar{X}\)</span> está cerca de la media poblacional <span class="math inline">\(\mu\)</span>, que es</p>
<p><span class="math display">\[\bar{X} \sim \mu = \pi  (aproximadamente)\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Ejemplo</li>
</ol>
<p>Todo lo que acabo de decir en el ejemplo anterior es esto: si le pregunta a 500 personas si les gusta Coca-Cola y 300 dicen que sí, ¡su mejor estimación para la proporción de personas que les gusta Coca-Cola es 300/500! Aquí <span class="math inline">\(\bar{X}= 300/500\)</span>. El punto es que esta simple idea es útil en casos mucho más complicados.</p>
<p>Cada parámetro de la población tiene un estadístico correspondiente y viceversa. Veamos:</p>
<p>Media de la muestra: media de la población</p>
<p>Porcentaje de muestra - porcentaje de población</p>
<p>Muestra mediana - mediana poblacional</p>
<p>Desviación estándar muestral - desviación estándar de la población</p>
<p>Muestra 1er cuartil - población 1er cuartil</p>
<p>etc ….</p>
<p>Cada uno de estos números de muestra se denomina estimación puntual.</p>
</div>
</div>
<div id="estimacion-por-intervalos" class="section level2">
<h2>Estimación por intervalos</h2>
<p>En la vida real, una estimación puntual rara vez es suficiente, por lo general también necesitamos una estimación del error en nuestra estimación.</p>
<p>Por ejemplo, suponga que hicimos una encuesta a los estudiantes subgraduados en el Colegio. Para eso entrevistamos a 150 estudiantes seleccionados al azar, y encontramos un GPA promedio (muestra) de 2.85. Realmente queremos saber la (población) promedio de GPA de todos los estudiantes de pregrado en el Colegio.</p>
<p>Ahora, el “2.85” es el GPA promedio específico para la muestra que recolectamos, si repetimos todo el proceso y encontramos una muestra diferente, también obtendremos un promedio de muestra diferente. Digamos que la media (población) del GPA para todos los estudiantes de pregrado es <span class="math inline">\(\mu_{gpa}\)</span>. Está bastante claro que <span class="math inline">\(\mu_{gpa} \neq 2.53\)</span>, pero con suerte <span class="math inline">\(\mu_{gpa}\)</span> está cerca de 2.85. Pero, qué tan cerca?</p>
<p>Una forma de responder a estas preguntas es encontrar una estimación de intervalo en lugar de una estimación puntual. Específicamente, consideraremos un tipo de estimación de intervalo llamado intervalo de confianza.</p>
<blockquote>
<p>¿Qué es un intervalo de confianza?</p>
</blockquote>
<p>Un intervalo de confianza es un rango de valores, derivado de los estadísticos de la muestra, que posiblemente incluya el valor de un parámetro de población desconocido. Debido a su naturaleza aleatoria, es poco probable que dos muestras de una población en particular produzcan intervalos de confianza idénticos. Sin embargo, si usted repitiera muchas veces su muestra, un determinado porcentaje de los intervalos de confianza resultantes incluiría el parámetro de población desconocido.</p>
<div class="figure">
<img src="interval.png" />

</div>
<p>En este caso, la línea negra horizontal representa el valor fijo de la media desconocida de la población, µ. Los intervalos de confianza azules verticales que se sobreponen a la línea horizontal contienen el valor de la media de la población. El intervalo de confianza rojo que está completamente por debajo de la línea horizontal no lo contiene. Un intervalo de confianza de 95% indica que 19 de 20 muestras (95%) de la misma población producirán intervalos de confianza que contendrán el parámetro de población.</p>
<p>Por ejemplo, un fabricante desea saber si la longitud media de los lápices que produce es diferente de la longitud objetivo. El fabricante toma una muestra aleatoria de lápices y determina que la longitud media de la muestra es 52 milímetros y el intervalo de confianza de 95% es (50,54). Por lo tanto, usted puede estar 95% seguro de que la longitud media de todos los lápices se encuentra entre 50 y 54 milímetros.</p>
<p>El intervalo de confianza se determina calculando una estimación de punto y luego determinando su margen de error.</p>
<p><strong>Estimación de punto</strong></p>
<p>Este valor individual estima un parámetro de la población usando los datos de la muestra. Por ejemplo, la estimación puntual mas usual es con base en la media muestral, es decir <span class="math inline">\(\bar{X}\)</span>.</p>
<p><strong>Margen de error</strong></p>
<p>Cuando usted utiliza estadísticos para estimar un valor, es importante recordar que, sin importar lo bien que esté diseñado su estudio, su estimación está sujeta a error de muestreo aleatorio. El margen de error cuantifica este error e indica la precisión de la estimación.</p>
<p>Usted probablemente ya entiende el margen de error, porque está relacionado con los resultados de las encuestas. Por ejemplo, una encuesta política podría indicar que el nivel de popularidad de un candidato es de 55% con un margen de error de 5%. Esto significa que el nivel de popularidad real es +/- 5% y, por lo tanto, se ubica entre 50% y 60%.</p>
<p>Para un intervalo de confianza bilateral, el margen de error es la distancia desde el estadístico estimado hasta cada el valor del intervalo de confianza. Cuando un intervalo de confianza es simétrico, el margen de error es la mitad del ancho del intervalo de confianza. Por ejemplo, la longitud media estimada de un árbol de levas es 600 mm y el intervalo de confianza oscila entre 599 y 601. El margen de error es 1.</p>
<p>Mientras mayor sea el margen de error, más ancho será el intervalo y menos seguro podrá estar usted del valor de la estimación de punto.</p>
<p>Finalmente el intervalo de confianza tiene la siguiente estructura:</p>
<p><strong>Valor puntual <span class="math inline">\(\pm\)</span> Valor crítico x error estándar</strong></p>
<p>Si consideramos el intervalo para la media poblacional, entonces el intervalo construido tendrá una confianza especifíca de la estimación correcta del valor del parámetro poblacional <span class="math inline">\(\mu\)</span>. En otras palabras, existe una confianza especificada de que <span class="math inline">\(\mu\)</span> se encuentre en algún lugar en el rango de números definidos dentro del intervalo.</p>
<p>En general, el <strong>nivel de confianza</strong> se simboliza con <span class="math inline">\((1 - \alpha).100 \%\)</span>, donde <span class="math inline">\(\alpha\)</span> es la proporción de las colas de la distribución que estan fuera del intervalo de confianza. La proporción de la cola superior e inferior de la distribución es <span class="math inline">\(\alpha/2\)</span></p>
<div id="intervalos-de-confianza-mas-precisos" class="section level3">
<h3>Intervalos de confianza más precisos</h3>
<p>Si el intervalo de confianza es demasiado ancho, usted no puede estar muy seguro del valor real de un parámetro, como por ejemplo la media. Sin embargo, puede utilizar varias estrategias para reducir el ancho de un intervalo de confianza y hacer que la estimación sea más precisa. Las siguientes características afectan el ancho del intervalo de confianza.</p>
<ul>
<li>Tamaño de la muestra</li>
<li>Variación en los datos</li>
<li>Tipo de intervalo</li>
<li>Nivel de confianza</li>
</ul>
<p><strong>Aumentar el tamaño de la muestra</strong></p>
<p>Con frecuencia, la manera más práctica de reducir el margen de error es aumentar el tamaño de la muestra. Por lo general, mientras más observaciones haya, más estrecho será el intervalo alrededor del estadístico de la muestra. Por lo tanto, se recomienda recolectar más datos para obtener una estimación más precisa de un parámetro de población.</p>
<p>Debe sopesar los beneficios de una mayor precisión con respecto al tiempo y los recursos adicionales necesarios para recopilar una muestra más grande. Por ejemplo, un intervalo de confianza que sea lo suficientemente estrecho como para contener solamente el parámetro de población requiere que se midan todos los sujetos de la población. Obviamente, esta estrategia por lo general resultaría muy poco práctica.</p>
<p><strong>Reducir la variabilidad</strong></p>
<p>Mientras menos varíen los datos, más precisa será la estimación de un parámetro de población. Eso se debe a que al reducirse la variabilidad de los datos, disminuye la desviación estándar y, por ende, el margen de error de la estimación. Aunque puede ser difícil reducir la variabilidad de los datos, a veces se puede lograr ajustando la forma en que se recolectan los datos. Por ejemplo, puede utilizar un diseño pareado para comparar dos grupos. También podría reducir la variabilidad mejorando el proceso, de manera que el proceso sea más consistente, o midiendo con mayor precisión.</p>
<p><strong>Utilizar un intervalo de confianza unilateral</strong></p>
<p>Un intervalo de confianza unilateral tiene un margen de error más pequeño que un intervalo de confianza bilateral. Sin embargo, un intervalo unilateral indica solo si un parámetro es menor que o mayor que un valor de corte. Un intervalo unilateral no proporciona información acerca del parámetro en la dirección opuesta. Por lo tanto, utilice un intervalo de confianza unilateral para aumentar la precisión de una estimación solo cuando le preocupe que la estimación sea mayor o menor que un valor de corte, pero no ambos.</p>
<p>Por ejemplo, una empresa de bebidas desea determinar la cantidad de sólidos disueltos en su agua potable. Mientras menos sólidos disueltos tenga el agua, mejor será. Cuando calculan un intervalo de confianza bilateral, el lado superior del intervalo es 18.4. Sin embargo, puesto que a la empresa solo le preocupa el límite superior, pueden calcular más bien un intervalo de confianza unilateral. El intervalo de confianza unilateral muestra que el límite superior de la cantidad de sólidos disueltos es incluso menor, 17.8 mg/L.</p>
<p><strong>Reducir el nivel de confianza</strong></p>
<p>La ventaja de un nivel de confianza más bajo es que se obtiene un intervalo de confianza más estrecho y más preciso. La desventaja es que se está menos seguro de que el intervalo de confianza contiene el parámetro de población de interés.</p>
<p>Entonces, reduzca el nivel de confianza solo si, en su situación, la ventaja de una mayor precisión supera a la desventaja de un menor grado de certeza. Por ejemplo, si es demasiado costoso aumentar el tamaño de la muestra en su estudio, disminuir el nivel de confianza reducirá la longitud del intervalo a expensas de perder algo de confianza.</p>
</div>
<div id="intervalo-de-confianza-para-la-media-de-una-poblacion" class="section level3">
<h3>Intervalo de confianza para la media de una población</h3>
<p>De una población de media <span class="math inline">\(\mu\)</span> y desviación estándar <span class="math inline">\(\sigma\)</span> se pueden tomar muestras de tamaño <span class="math inline">\(n\)</span>. Como vimos anteriormente cada una de estas muestras tiene a su vez una media y que la media de todas las medias muestrales coincide con la media poblacional: <span class="math inline">\(\mu_{\bar{x}}=\mu\)</span>.</p>
<p>Pero además, si el tamaño de las muestras es lo suficientemente grande, (n &gt;30) o la distribución poblacional es normal, la distribución de medias muestrales es, prácticamente, una distribución normal (o gaussiana) con media <span class="math inline">\(\mu\)</span> y una desviación típica dada por la siguiente expresión:</p>
<p><span class="math display">\[\sigma_{\bar{x}}=\dfrac{\sigma}{\sqrt{n}}\]</span></p>
<p>Entonces tenemos que la media muestral <span class="math inline">\(\bar{X}\)</span> se comporta aproximadamente como una variable aleatoria normal con media igual a la media poblacional <span class="math inline">\(\mu\)</span> y con desviación estándar <span class="math inline">\(\sigma\)</span> igual a la desviación poblacional dividida por la raíz cuadrada del tamaño de la muestra, siempre que sea grande. Esto es:</p>
<p><span class="math display">\[\bar{X} \sim Normal(\mu,\frac{\sigma}{\sqrt{n}})\]</span></p>
<p>Estandarizando, donde <span class="math display">\[Z = \dfrac{\bar{X}-\mu}{\dfrac{\sigma}{\sqrt{n}}}\]</span></p>
<p>tenemos:</p>
<p><span class="math display">\[Z \sim Normal(0,1)\]</span></p>
<p>En esta distribución normal de medias se puede calcular el intervalo de confianza donde se encontrará la media poblacional si solo se conoce una media muestral <span class="math inline">\(\bar{X}\)</span>, con un nivel de confianza determinado. Habitualmente se manejan valores de confianza del 95 % y del 99 %. A estos valores de confianza se les nota por <span class="math inline">\(1-\alpha\)</span> (debido a que <span class="math inline">\(\alpha\)</span> es la probabilidad de que la media muestral no este en el intervalo. Tener presente:</p>
<ol style="list-style-type: decimal">
<li><p><em><span class="math inline">\((1-\alpha)*100 \%\)</span></em> es el nivel de confianza o confiabilidad.</p></li>
<li><p><em><span class="math inline">\(\alpha\)</span></em> es el nivel de significancia.</p></li>
</ol>
<p>Para construir el intervalo de confianza se necesita encontrar en valor crítico <span class="math inline">\(Z_{\alpha/2}\)</span> que equivale a un percentil de la distribución normal estándar.</p>
<div class="figure">
<img src="int.png" />

</div>
<blockquote>
<p>¿Cómo encontrar el valor crítico <span class="math inline">\(Z_{\alpha/2}\)</span>?</p>
</blockquote>
<p>Supongamos un nivel de confianza del 95 %, por tanto <span class="math inline">\(\alpha=0.5\)</span>, entonces ¿Cuanto es <span class="math inline">\(Z_{\alpha/2}\)</span>?, para responder esto se pueden usar tablas estadisticas de la distribución nnormal estándar, pero esto no es muy atractivo en esta época. Podemos usar <code>RStudio</code>, veamos</p>
<p>Si, <span class="math inline">\(\alpha=0.5\)</span>, entonces <span class="math inline">\(\alpha/2=0.025\)</span>, esto quiere decir que:</p>
<p><span class="math display">\[P(Z&lt; z_{\alpha/2})=0.025\]</span> Para saber el valor del percentil <span class="math inline">\(z_{\alpha/2}\)</span> usamos la función <code>qnorm()</code>, como sigue para un 95 % de confianza</p>
<pre class="r"><code>qnorm(0.025,0,1)</code></pre>
<pre><code>## [1] -1.959964</code></pre>
<p>Y si <span class="math inline">\(\alpha=0.1\)</span>, entonces <span class="math inline">\(Z_{\alpha/2}\)</span> es decir con un 90 % de confianza</p>
<pre class="r"><code>qnorm(0.05,0,1)</code></pre>
<pre><code>## [1] -1.644854</code></pre>
<p>También, si <span class="math inline">\(\alpha=0.01\)</span>, entonces <span class="math inline">\(Z_{\alpha/2}\)</span> es decir con un 99 % de confianza</p>
<pre class="r"><code>qnorm(0.005,0,1)</code></pre>
<pre><code>## [1] -2.575829</code></pre>
<p>En resumen,</p>
<table style="width:51%;">
<colgroup>
<col width="19%" />
<col width="12%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th>Nivel de confianza</th>
<th>Nivel de significancia <span class="math inline">\(\alpha\)</span></th>
<th>Punto crítico <span class="math inline">\(Z_{\alpha/2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>99 %</td>
<td>0.01</td>
<td>2.575</td>
</tr>
<tr class="even">
<td>95 %</td>
<td>0.05</td>
<td>1.960</td>
</tr>
<tr class="odd">
<td>90 %</td>
<td>0.1</td>
<td>1.645</td>
</tr>
</tbody>
</table>
</div>
<div id="intervalo-para-mu-con-sigma2-conocida" class="section level3">
<h3>Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma^2\)</span> conocida</h3>
<p>Si conocemos la desviación estándar poblacional el intervalo de confianza para <span class="math inline">\(\mu\)</span> esta definido de la siguiente manera:</p>
<p><span class="math display">\[\bar{X} \pm Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}\]</span></p>
<p>Donde,</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\bar{X} - Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\bar{X} + Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}\)</span></p>
<p>Por tanto, el intervalo para la media <span class="math inline">\(\mu\)</span> es</p>
<p><span class="math display">\[\Big(\bar{X} - Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}} , \bar{X} + Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}\Big)\]</span></p>
<blockquote>
<p>Ejemplos</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Los siguientes datos corresponden a una muestra de la estatura de los estudiantes (en centímetros) en cierta universidad. Se sabe que la población es normal con varianza <span class="math inline">\(\sigma^2=7\)</span>.</li>
</ol>
<p>159, 179, 164, 165, 165, 168, 171, 162, 169, 168, 179, 162, 174, 168, 168, 168, 167, 157, 171, 176, 179, 163, 170, 163, 171, 161, 177, 156, 158, 171, 162, 168, 170, 168, 172, 170, 171, 169, 165, 164, 156, 170, 163, 164, 179, 165, 149, 162, 167, 172</p>
<ol style="list-style-type: lower-alpha">
<li>Estimar la media poblacional de la estatura en los estudiantes mediante estimación puntual</li>
</ol>
<p>La estimación puntual mediante la media es:</p>
<pre class="r"><code>estatura &lt;- c(159, 179, 164, 165, 165, 168, 171, 162, 169, 168, 179, 162, 174, 168, 168, 168, 167, 157, 171, 176, 179, 163, 170, 163, 171, 161, 177, 156, 158, 171, 162, 168, 170, 168, 172, 170, 171, 169, 165, 164, 156, 170, 163, 164, 179, 165, 149, 162, 167, 172)
mean(estatura)</code></pre>
<pre><code>## [1] 167.1</code></pre>
<p>Es decir que <span class="math inline">\(\bar{X}=167.1 cm\)</span> es la estimación de la media poblacional.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Construya un intervalo de confianza para estimar la media poblacional de la estatura de los estudiantes. Con un nivel de confianza del 95 %.</li>
</ol>
<p>Para este caso tenemos los siguientes datos:</p>
<p><span class="math inline">\(n=50\)</span></p>
<p><span class="math inline">\(\bar{X}=167.1\)</span></p>
<p><span class="math inline">\(\sigma=\sqrt{7}=2.645\)</span></p>
<p>Necesitamos el valor crítico de la distribución normal estándar en <span class="math inline">\(Z_{\alpha/2}\)</span></p>
<pre class="r"><code>qnorm(0.025,0,1)</code></pre>
<pre><code>## [1] -1.959964</code></pre>
<p>Es decir <span class="math inline">\(Z_{0.005}=1.960\)</span>, tomando el valor positivo.</p>
<p>Luego:</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\bar{X} - Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}=167.1 - 1.960*\dfrac{2.645}{\sqrt{50}}=166.36\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\bar{X} + Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}=167.1 + 1.960*\dfrac{9000}{\sqrt{50}}=167.83\)</span></p>
<p>Por lo tanto el intervalo de confianza del 95 % esta dado por</p>
<p><span class="math display">\[\Big(166.36, 167.83 \Big)cm \]</span></p>
<p>Conclusión: Podemos afirmar con una confiabilidad del 95 % que el promedio de la estatura en los estudiantes esta dentro del intervalo de confianza. Es decir entre <span class="math inline">\(166.36\)</span> y <span class="math inline">\(167.83\)</span>.</p>
<ol start="2" style="list-style-type: decimal">
<li>Una prestigiosa cadena de restaurantes está pensando en abrir una nueva franquicia. Para tomar la decisión se basan en las ventas promedio mensuales de 12 restaurantes activos en cierta ciudad que son de su propiedad. Ellos piensan que si dichas ventas en promedio son mayores a <span class="math inline">\(30,000\)</span> al mes, entonces la decisión será viable. Se conoce que la desviación estándar poblacional es <span class="math inline">\(\sigma=\$9000\)</span>. Los datos son los siguientes:</li>
</ol>
<p>28959, 33000, 29383, 20203, 15145, 31767, 27342, 12476, 24720, 25308, 1933, 27284</p>
<ol style="list-style-type: lower-alpha">
<li>Use estimación puntual para estimar la media poblacional de las ventas. ¿Que le recomienda al dueño del restaurante?</li>
</ol>
<pre class="r"><code>ventas &lt;- c(28959, 33000, 29383, 20203, 15145, 31767, 27342, 12476, 24720, 25308,  1933, 27284)
mean(ventas)</code></pre>
<pre><code>## [1] 23126.67</code></pre>
<p>Tenemos que <span class="math inline">\(\bar{X}=\$23126.67\)</span> es la estimación puntual del promedio mensual de ventas. Por lo tanto según la meta del dueño del restaurante no es recomendable que abra uno nuevo.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Construya un intervalo de confianza para estimar el promedio de ventas mensuales. ¿Es viable abrir un nuevo restaurante en la ciudad?. Use un nivel de confianza del 99 %.</li>
</ol>
<p>Para este caso tenemos los siguientes datos:</p>
<p><span class="math inline">\(n=12\)</span></p>
<p><span class="math inline">\(\bar{X}=\$23126.67\)</span></p>
<p><span class="math inline">\(\sigma=9000\)</span></p>
<p>Necesitamos el valor crítico de la distribución normal estándar en <span class="math inline">\(Z_{\alpha/2}\)</span></p>
<pre class="r"><code>qnorm(0.005,0,1)</code></pre>
<pre><code>## [1] -2.575829</code></pre>
<p>Es decir <span class="math inline">\(Z_{0.005}=2.575\)</span>, tomando el valor positivo.</p>
<p>Luego:</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\bar{X} - Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}=23126.67 - 2.575*\dfrac{9000}{\sqrt{12}}=16436.62\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\bar{X} + Z_{\alpha/2}\dfrac{\sigma}{\sqrt{n}}=23126.67 + 2.575*\dfrac{9000}{\sqrt{12}}=29816.71\)</span></p>
<p>Por lo tanto el intervalo de confianza del 99 % esta dado por</p>
<p><span class="math display">\[\Big(16436.62, 29816.71 \Big)\$ \]</span></p>
<p>Conclusión: Podemos afirmar con una confiabilidad del 99 % que el promedio de ventas mensuales esta dentro del intervalo de confianza. Es decir entre <span class="math inline">\(\$16436.62\)</span> y <span class="math inline">\(\$29816.71\)</span>.</p>
<p><strong>También la apertura de un nuevo restaurante NO puede ser viable, dado a que la meta de $ 30000 mil propuesta por el dueño del restaurante NO esta dentro del intervalo</strong>.</p>
</div>
<div id="intervalo-para-mu-con-sigma2-desconocida" class="section level3">
<h3>Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma^2\)</span> desconocida</h3>
<p><span class="math display">\[\bar{X} \pm t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}\]</span></p>
<p>Donde,</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\bar{X} - t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\bar{X} + t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}\)</span></p>
<p>Por tanto, el intervalo para la media <span class="math inline">\(\mu\)</span> es</p>
<p><span class="math display">\[\Big(\bar{X} - t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}} , \bar{X} + t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}\Big)\]</span></p>
<p>Donde <span class="math inline">\(n-1\)</span>son los grados de libertad para estimar <span class="math inline">\(\mu\)</span>. Tambén <span class="math inline">\(t_{n-1,\alpha/2}\)</span> es la distribución t-student con <span class="math inline">\(n-1\)</span> grados de libertad. En <code>RStudio</code> se puede usar el comando <code>qt(p,n-1)</code> para encontrar el valor crítico de la distribución.</p>
<blockquote>
<p>Ejemplos</p>
</blockquote>
<p>Supongamos que en el ejemplo de la cadena de restaurantes, desconocemos la desviació poblacional <span class="math inline">\(\sigma\)</span>, por lo tanto tenemos que calcular la desviación muestral <span class="math inline">\(S\)</span>. Responder las preguntas a) y b) en este nuevo escenario.</p>
<p>Tenemos que calcular la desviación estándar de los datos</p>
<pre class="r"><code>ventas &lt;- c(28959, 33000, 29383, 20203, 15145, 31767, 27342, 12476, 24720, 25308,  1933, 27284)
mean(ventas)</code></pre>
<pre><code>## [1] 23126.67</code></pre>
<pre class="r"><code>sd(ventas)</code></pre>
<pre><code>## [1] 9157.75</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>Tenemos que <span class="math inline">\(\bar{X}=\$23126.67\)</span>, es la estimación puntual del promedio mensual de ventas. Por lo tanto según la meta del dueño del restaurante no es recomendable que abra un nuevo restaurante.</p></li>
<li><p>Para este caso tenemos los siguientes datos:</p></li>
</ol>
<p><span class="math inline">\(n=12\)</span></p>
<p><span class="math inline">\(\bar{X}=\$23126.67\)</span></p>
<p><span class="math inline">\(S=9157.75\)</span></p>
<p>Necesitamos el valor de la distribución t-studen en <span class="math inline">\(t_{n-1,\alpha/2}\)</span></p>
<pre class="r"><code>qt(0.005,11)</code></pre>
<pre><code>## [1] -3.105807</code></pre>
<p>Es decir <span class="math inline">\(t_{11,0.005}=3.1058\)</span>, tomando el valor positivo.</p>
<p>Luego:</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\bar{X} - t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}=23126.67 - 3.1058*\dfrac{9157.75}{\sqrt{12}}=14916.13\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\bar{X} + t_{n-1,\alpha/2}\dfrac{S}{\sqrt{n}}=23126.67 + 3.1058*\dfrac{9157.75}{\sqrt{12}}=31337.20\)</span></p>
<p>Por lo anto el intervalo de confianza esta dado por</p>
<p><span class="math display">\[\Big(14916.13,31337.20\Big)\$ \]</span></p>
<p>Conclusión: Podemos afirmar con una confiabilidad del 99 % que el promedio de ventas mensuales esta dentro del intervalo de confianza. Es decir entre <span class="math inline">\(\$14916.13\)</span> y <span class="math inline">\(\$31337.20\)</span>.</p>
<p><strong>También la apertura de un nuevo restaurante puede ser viable, dado a que la meta de $ 30000 mil propuesta por el dueño del restaurante esta dentro del intervalo</strong>.</p>
</div>
</div>
<div id="intervalo-de-confianza-para-proporciones" class="section level2">
<h2>Intervalo de confianza para proporciones</h2>
<p>El intervalo de confianza para estimar una proporción <span class="math inline">\(\pi\)</span>, conocida como una proporción muestral  de una muestra de tamaño <span class="math inline">\(n\)</span>, a un nivel de confianza del <span class="math inline">\((1-\alpha)100 \%\)</span> es:</p>
<p><span class="math display">\[\hat{p}\pm Z_{\alpha/2}\sqrt{\dfrac{\hat{p}(1-\hat{p})}{n}} \]</span> Donde,</p>
<p><strong>Límite Inferior</strong>: <span class="math inline">\(\hat{p} - Z_{\alpha/2}\sqrt{\dfrac{\hat{p}(1-\hat{p})}{n}}\)</span></p>
<p><strong>Límite Superior</strong>: <span class="math inline">\(\hat{p} + Z_{\alpha/2}\sqrt{\dfrac{\hat{p}(1-\hat{p})}{n}}\)</span></p>
<p>Es decir el intervalo es</p>
<p><span class="math display">\[\Big(\hat{p} - Z_{\alpha/2}\sqrt{\dfrac{\hat{p}(1-\hat{p})}{n}}, \hat{p} + Z_{\alpha/2}\sqrt{\dfrac{\hat{p}(1-\hat{p})}{n}}\Big)\]</span></p>
<blockquote>
<p>Ejemplos</p>
</blockquote>
<ol style="list-style-type: decimal">
<li><p>Volvamos al ejemplo de los estudiantes a los que les gusta la comida de la cafeteria colegial, suponga que fueron preguntados 300 estudiantes del Colegio y de ellos 180 contestaron que si les gusta la comida. Construir intervalos de confianza del 99 %, 95 % y 90 % para estimar la proporción de estudiantes a los que les gusta la comida de la cafeteria.</p></li>
<li><p>De una muestra de 180 personas que son fumadores frecuentes se econtró que el 67 % de ellos presentan problemas respiratorios. Estimar la proporción poblacional mediante intervalos de confianza de personas que son fumadoras y NO presentan dificultad al respirar. Use una confiabilidad del 95 % y 90 %.</p></li>
</ol>
</div>
<div id="ejercicios-de-repaso" class="section level2">
<h2>Ejercicios de repaso</h2>
<ol style="list-style-type: decimal">
<li>Digamos que <span class="math inline">\(X \sim Binom(22,0.45)\)</span>. Mediante aproximación normal encuentre:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math inline">\(P(X = 4)\)</span></p></li>
<li><p><span class="math inline">\(P(2 &lt; X &lt; 5)\)</span></p></li>
<li><p><span class="math inline">\(P(3 \leq X \leq 6)\)</span></p></li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Sea <span class="math inline">\(X \sim Normal(5,7)\)</span>, <span class="math inline">\(Y \sim Normal(2,10)\)</span> y <span class="math inline">\(W \sim Normal(10,12)\)</span></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Encuentre la distribución de la media muestral de <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span> y <span class="math inline">\(W\)</span>, es decir</li>
</ol>
<p><span class="math display">\[\bar{X} \sim \]</span> <span class="math display">\[\bar{Y} \sim\]</span> <span class="math display">\[\bar{W} \sim\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Mediante estandarizacoón encuentre <span class="math inline">\(P(\bar{X} &gt; 3)\)</span>, <span class="math inline">\(P(\bar{Y} &lt; 2)\)</span> y <span class="math inline">\(P(3 \leq \bar{W} \leq 6)\)</span></li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li><p>Una muestra de tamaño 49 tiene un promedio muestral de 35 y una desviación estándar muestral de 14. Construya un intervalo de confianza del 98 % de confiabilidad para la media de la población usando esta información. Interpreta su significado.</p></li>
<li><p>Una muestra aleatoria de 120 estudiantes de una universidad de EEUU arroja un promedio del GPA igual a 2.71. Suponga que conocemos la desviación estándar poblacional y es igual a 0.55. Construya un intervalo de confianza del 90 % para el GPA promedio de todos los estudiantes en la universidad.</p></li>
<li><p>A cuatrocientos adultos trabajadores seleccionados al azar en un determinado estado, se les preguntó la distancia desde su hogar hasta su lugar de trabajo. La distancia promedio fue de 8.84 millas con una desviación estándar de 2.70 millas. Construya intervalos de confianza del 90 %, 94 %, 97 % para la distancia media entre el hogar y el trabajo de todos los residentes de este estado.</p></li>
<li><p>Para estimar el número de calorías en una porción de carne de pechuga de pollo en cubos, se mide la cantidad de calorías en una muestra de 15 platos de carne separadas. La media muestral es de 211.8 calorías con una desviación estándar de muestra de 0.9 calorías. Suponiendo que el contenido calórico de todas las carnes de pollo se distribuye normalmente, construya un intervalo de confianza del 95% para la cantidad media de calorías en un plato de carne.</p></li>
<li><p>Para estimar la proporción de estudiantes en una universidad grande que son mujeres, se selecciona una muestra aleatoria de 120 estudiantes. Hay 75 alumnas en la muestra. Construya un intervalo de confianza del 90 % y 99 % para la proporción de todos los estudiantes de la universidad que son mujeres.</p></li>
<li><p>En una muestra aleatoria de 900 adultos, 42 se definieron a sí mismos como vegetarianos.</p></li>
</ol>
<ul>
<li><p>Proporcione una estimación puntual de la proporción de adultos que se definirían como vegetarianos.</p></li>
<li><p>Construya un intervalo de confianza del 80 % de confianza para la proporción de todos los adultos que se definirían a sí mismos como vegetarianos.</p></li>
</ul>
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
