<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Pruebas de Hipótesis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Didier Murillo</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Teaching.html">Teaching</a>
</li>
<li>
  <a href="about.html">About Me</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Pruebas de Hipótesis</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#pruebas-de-hipotesis">Pruebas de hipótesis</a><ul>
<li><a href="#introduccion">Introducción</a></li>
<li><a href="#formalismo-en-pruebas-de-hipotesis">Formalismo en pruebas de hipótesis</a></li>
<li><a href="#pruebas-de-hipotesis-para-la-media-poblacional">Pruebas de hipótesis para la media poblacional</a></li>
<li><a href="#p---values">p - values</a></li>
<li><a href="#prueba-de-hipotesis-para-una-proporcion">Prueba de hipótesis para una proporción</a></li>
</ul></li>
<li><a href="#pruebas-de-hipotesis-con-rstudio.">Pruebas de hipótesis con RStudio.</a><ul>
<li><a href="#pruebas-de-hipotesis-para-la-media-poblacional-mu-usando-rstudio">Pruebas de hipótesis para la media poblacional <span class="math inline">\(\mu\)</span> usando <code>RStudio</code></a></li>
<li><a href="#caso-1-prueba-de-hipotesis-para-mu-con-sigma-conocida"><strong>Caso 1: Prueba de hipótesis para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma\)</span> conocida</strong></a></li>
<li><a href="#caso-2-intervalo-para-mu-con-sigma-desconocida"><strong>Caso 2: Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma\)</span> desconocida</strong></a></li>
<li><a href="#pruebas-de-hipotesis-para-la-proporcion-poblacional-p-usando-rstudio">Pruebas de hipotesis para la proporción poblacional <span class="math inline">\(p\)</span> usando <code>RStudio</code></a></li>
</ul></li>
<li><a href="#ejercicios-de-repaso">Ejercicios de repaso</a></li>
</ul>
</div>

<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

</style>
<div id="pruebas-de-hipotesis" class="section level2">
<h2>Pruebas de hipótesis</h2>
<div id="introduccion" class="section level3">
<h3>Introducción</h3>
<div id="una-prueba-de-hipotesis-es-un-metodo-estadistico-que-responde-a-una-pregunta-particular-de-forma-si-o-no." class="section level4">
<h4>Una prueba de hipótesis es un método estadístico que responde a una pregunta particular de forma Sí o No.</h4>
</div>
<div id="ejemplo-el-gpa-promedio-de-estudiantes-universitarios-es-menor-a-2.8" class="section level4">
<h4>Ejemplo: ¿El GPA promedio de estudiantes universitarios es menor a 2.8?</h4>
</div>
<div id="ejemplo-el-ingreso-promedio-de-los-hombres-en-puerto-rico-es-mas-alto-que-el-ingreso-promedio-de-las-mujeres" class="section level4">
<h4>Ejemplo: ¿El ingreso promedio de los hombres en Puerto Rico es más alto que el ingreso promedio de las mujeres?</h4>
</div>
<div id="una-prueba-de-hipotesis-generalmente-se-expresa-en-forma-de-dos-enunciados-en-lugar-de-una-pregunta.-estas-declaraciones-se-llaman-la-hipotesis-nula-h_0-y-la-hipotesis-alterna.-h_a" class="section level4">
<h4>Una prueba de hipótesis generalmente se expresa en forma de dos enunciados, en lugar de una pregunta. Estas declaraciones se llaman la hipótesis nula (<span class="math inline">\(H_0\)</span>) y la hipótesis alterna. (<span class="math inline">\(H_a\)</span>)</h4>
</div>
<div id="h_0-y-h_a-corresponden-a-dos-enunciados-en-lugar-de-hacer-una-sola-pregunta." class="section level4">
<h4><span class="math inline">\(H_0\)</span> y <span class="math inline">\(H_a\)</span> corresponden a dos enunciados en lugar de hacer una sola pregunta.</h4>
</div>
<div id="ejemplos" class="section level4">
<h4>Ejemplos:</h4>
</div>
<div id="podemos-considerar-el-planteamiento-de-las-siguientes-hipotesis-para-el-gpa-de-los-estudiantes-en-puerto-rico." class="section level4">
<h4>1. Podemos considerar el planteamiento de las siguientes hipótesis para el GPA de los estudiantes en Puerto Rico.</h4>
</div>
<div id="h_0-el-gpa-promedio-de-los-estudiantes-subgraduados-en-puerto-rico-es-igual-a-2.8" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: El GPA promedio de los estudiantes subgraduados en Puerto Rico es igual a 2.8</h4>
</div>
<div id="h_a-el-gpa-promedio-de-los-estudiantes-subgraduados-en-puerto-rico-es-mayor-a-2.8" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: El GPA promedio de los estudiantes subgraduados en Puerto Rico es mayor a 2.8</h4>
</div>
<div id="otra-forma-de-escribir-estas-hipotesis-es-mediante-un-parametro-poblacional-que-en-este-caso-es-el-promedio-poblacional-mu." class="section level4">
<h4>Otra forma de escribir estas hipótesis es mediante un parámetro poblacional, que en este caso, es el promedio poblacional <span class="math inline">\(\mu\)</span>.</h4>
</div>
<div id="entonces-las-correspondientes-hipotesis-para-el-ejemplo-1-son" class="section level4">
<h4>Entonces, las correspondientes hipótesis para el ejemplo 1 son:</h4>
</div>
<div id="h_0-mu-2.8" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 2.8\)</span></h4>
</div>
<div id="h_a-mu-2.8" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; 2.8\)</span></h4>
</div>
<div id="devengan-mas-dinero-los-hombres-que-las-mujeres-en-puerto-rico" class="section level4">
<h4>2. ¿Devengan más dinero los hombres que las mujeres en Puerto Rico?</h4>
</div>
<div id="h_0-el-ingreso-mensual-promedio-es-igual-en-hombres-y-en-mujeres." class="section level4">
<h4><span class="math inline">\(H_0\)</span>: El ingreso mensual promedio es igual en hombres y en mujeres.</h4>
</div>
<div id="h_a-el-ingreso-mensual-promedio-es-mayor-en-hombres-que-en-mujeres." class="section level4">
<h4><span class="math inline">\(H_a\)</span>: El ingreso mensual promedio es mayor en hombres que en mujeres.</h4>
</div>
<div id="para-este-caso-el-parametro-es-el-ingreso-promedio-de-hombres-y-mujeres-es-decir-mu_m-y-mu_f-respectivamente.-entonces" class="section level4">
<h4>Para este caso el parámetro es, el ingreso promedio de hombres y mujeres, es decir, <span class="math inline">\(\mu_M\)</span> y <span class="math inline">\(\mu_F\)</span> respectivamente. entonces</h4>
</div>
<div id="h_0-mu_m-mu_f" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_M = \mu_F\)</span></h4>
</div>
<div id="h_a-mu_m-mu_f" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_M &gt; \mu_F\)</span></h4>
</div>
<div id="uno-de-los-errores-mas-comunes-al-plantear-las-hipotesis-para-la-media-poblacional-mu-es-usar-la-media-muestra-barx." class="section level4">
<h4>Uno de los errores más comunes al plantear las hipótesis para la media poblacional <span class="math inline">\(\mu\)</span>, es usar la media muestra <span class="math inline">\(\bar{X}\)</span>.</h4>
</div>
</div>
<div id="formalismo-en-pruebas-de-hipotesis" class="section level3">
<h3>Formalismo en pruebas de hipótesis</h3>
<div id="podemos-organizar-la-metodologia-para-realizar-pruebas-de-hipotesis-en-unos-simples-pasos" class="section level4">
<h4>Podemos organizar la metodología para realizar pruebas de hipótesis en unos simples pasos:</h4>
</div>
<div id="definir-el-parametro-de-interes-y-los-datos-del-problema." class="section level4">
<h4>1. Definir el parámetro de interés y los datos del problema.</h4>
</div>
<div id="plantear-las-hipotesis" class="section level4">
<h4>2. Plantear las hipótesis</h4>
</div>
<div id="metodo-de-analisis-y-supuestos" class="section level4">
<h4>3. Método de análisis y supuestos</h4>
</div>
<div id="encontrar-el-valor-critico-de-la-distribucion-luego-especificar-la-region-de-rechazo-y-no-rechazo." class="section level4">
<h4>4. Encontrar el valor crítico de la distribución, luego especificar la región de rechazo y no rechazo.</h4>
</div>
<div id="decision-y-conclusion." class="section level4">
<h4>5. Decisión y conclusión.</h4>
</div>
</div>
<div id="pruebas-de-hipotesis-para-la-media-poblacional" class="section level3">
<h3>Pruebas de hipótesis para la media poblacional</h3>
<div id="para-la-media-poblacional-donde-mu_0-es-un-numero-fijo-definido-por-el-investigador-las-hipotesis-se-pueden-definir-de-una-de-las-tres-formas-siguientes" class="section level4">
<h4>Para la media poblacional, donde <span class="math inline">\(\mu_0\)</span> es un número fijo definido por el investigador, las hipótesis se pueden definir de una de las tres formas siguientes:</h4>
</div>
<div id="prueba-a-cola-izquierda" class="section level4">
<h4>1. Prueba a cola izquierda:</h4>
</div>
<div id="h_0-mu-mu_0" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-mu_0" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &lt; \mu_0\)</span></h4>
</div>
<div id="prueba-a-cola-derecha" class="section level4">
<h4>2. Prueba a cola derecha:</h4>
</div>
<div id="h_0-mu-mu_0-1" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-mu_0-1" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; \mu_0\)</span></h4>
</div>
<div id="prueba-a-dos-colas" class="section level4">
<h4>3. Prueba a dos colas:</h4>
</div>
<div id="h_0-mu-mu_0-2" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-neq-mu_0" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu \neq \mu_0\)</span></h4>
<blockquote>
<p>Caso 1: La varianza poblacional <span class="math inline">\(\sigma^2\)</span> es conocida</p>
</blockquote>
</div>
<div id="en-algunos-casos-por-algun-motivo-se-es-conocida-la-varianza-poblacional-sigma2-y-un-valor-especifico-de-mu-como-mu_0.-en-este-caso-el-metodo-de-analisis-suponiendo-que-los-datos-provienen-de-una-distribucion-normal-y-que-la-varianza-es-conocida-es-mediante-la-distribucion-normal-estandar-z." class="section level4">
<h4>En algunos casos, por algún motivo se es conocida la varianza poblacional <span class="math inline">\(\sigma^2\)</span> y un valor específico de <span class="math inline">\(\mu\)</span> como <span class="math inline">\(\mu_0\)</span>. En este caso el método de análisis, suponiendo que los datos provienen de una distribución normal y que la varianza es conocida es mediante la distribución normal estándar <span class="math inline">\(Z\)</span>.</h4>
</div>
<div id="el-estadistico-de-prueba-es" class="section level4">
<h4>El estadístico de prueba es,</h4>
</div>
<div id="zdfracbarx-mu_0sigmasqrtn" class="section level4">
<h4><span class="math display">\[Z^*=\dfrac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\]</span></h4>
</div>
<div id="en-general-podemos-plantear-tres-tipos-de-hipotesis-para-la-media-poblacional-en-este-caso." class="section level4">
<h4>En general podemos plantear tres tipos de hipótesis para la media poblacional en este caso.</h4>
</div>
<div id="prueba-a-cola-izquierda-1" class="section level4">
<h4>1. Prueba a cola izquierda</h4>
</div>
<div id="h_0-mu-mu_0-3" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-mu_0-2" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &lt; \mu_0\)</span></h4>
</div>
<div id="en-este-caso-la-region-de-rechazo-esta-dada-por-los-valores-de-z-menores-que--z_alpha." class="section level4">
<h4>En este caso la región de rechazo está dada por los valores de <span class="math inline">\(Z\)</span> menores que <span class="math inline">\(-Z_{\alpha}\)</span>.</h4>
</div>
<div id="el-criterio-de-decision-es-se-decide-rechazar-h_0-si" class="section level4">
<h4>El criterio de decisión, es: Se decide rechazar <span class="math inline">\(H_0\)</span> si,</h4>
</div>
<div id="z--z_alpha" class="section level4">
<h4><span class="math display">\[Z^* &lt; -Z_{\alpha}\]</span></h4>
</div>
<div id="prueba-a-cola-derecha-1" class="section level4">
<h4>2. Prueba a cola derecha</h4>
</div>
<div id="h_0-mu-mu_0-4" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-mu_0-3" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; \mu_0\)</span></h4>
</div>
<div id="en-este-caso-la-region-de-rechazo-esta-dada-por-los-valores-de-z-mayores-que-z_alpha." class="section level4">
<h4>En este caso la región de rechazo está dada por los valores de <span class="math inline">\(Z\)</span> mayores que <span class="math inline">\(Z_{\alpha}\)</span>.</h4>
</div>
<div id="el-criterio-de-decision-es-se-decide-rechazar-h_0-si-1" class="section level4">
<h4>El criterio de decisión, es: Se decide rechazar <span class="math inline">\(H_0\)</span> si,</h4>
</div>
<div id="z-z_alpha" class="section level4">
<h4><span class="math display">\[Z^* &gt; Z_{\alpha}\]</span></h4>
</div>
<div id="prueba-a-dos-colas-1" class="section level4">
<h4>3. Prueba a dos colas</h4>
</div>
<div id="h_0-mu-mu_0-5" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span></h4>
</div>
<div id="h_a-mu-neq-mu_0-1" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu \neq \mu_0\)</span></h4>
</div>
<div id="en-este-caso-la-region-de-rechazo-esta-dada-por-los-valores-de-z-mayores-que-z_alpha2-y-menores-que--z_alpha2." class="section level4">
<h4>En este caso la región de rechazo está dada por los valores de <span class="math inline">\(Z\)</span> mayores que <span class="math inline">\(Z_{\alpha/2}\)</span> y menores que <span class="math inline">\(-Z_{\alpha/2}\)</span>.</h4>
</div>
<div id="el-criterio-de-decision-es-se-decide-rechazar-h_0-si-tenemos" class="section level4">
<h4>El criterio de decisión, es: Se decide rechazar <span class="math inline">\(H_0\)</span> si tenemos:</h4>
</div>
<div id="z-z_alpha2" class="section level4">
<h4><span class="math display">\[|Z^*| &gt; Z_{\alpha/2}\]</span></h4>
</div>
<div id="las-regiones-de-rechazo-para-cada-caso-de-hipotesis-alterna-son-las-siguientes" class="section level4">
<h4><strong>Las regiones de rechazo para cada caso de hipótesis alterna son las siguientes:</strong></h4>
<div class="figure">
<img src="test-z.jpg" />

</div>
</div>
<div id="que-es-alpha" class="section level4">
<h4><strong>¿Que es <span class="math inline">\(\alpha\)</span>?</strong></h4>
</div>
<div id="es-la-significancia-estadistica-representa-el-valor-para-la-probabilidad-de-rechazar-la-hipotesis-nula-h_0-dado-que-h_0-es-cierta-y-es-conocido-como-el-error-tipo-i." class="section level4">
<h4>Es la significancia estadística, representa el valor para la probabilidad de rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, dado que <span class="math inline">\(H_0\)</span> es cierta y es conocido como el error tipo I.</h4>
</div>
<div id="como-concluir" class="section level4">
<h4><strong>¿Cómo concluir?</strong></h4>
</div>
<div id="si-la-decision-es-rechazar-la-hipotesis-nula-h_0-entonces-se-debe-concluir-con-base-en-la-hipotesis-alterna-h_a." class="section level4">
<h4>Si la decisión es rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, entonces se debe concluir con base en la hipótesis alterna <span class="math inline">\(H_a\)</span>.</h4>
<blockquote>
<p>Ejemplos</p>
</blockquote>
</div>
<div id="en-los-ultimos-cinco-anos-el-puntaje-promedio-en-el-examen-final-de-un-curso-de-estadistica-fue-73-puntos.-este-semestre-una-clase-con-27-estudiantes-utilizando-un-nuevo-libro-de-texto-obtuvo-en-promedio-78.1.-se-sabe-que-la-varianza-poblacional-es-sigma249.-hay-evidencia-para-afirmar-que-el-nuevo-libro-de-texto-hizo-que-el-resultado-del-examen-final-fuera-mas-alto.-use-un-nivel-de-significancia-del-5" class="section level4">
<h4>1. En los últimos cinco años el puntaje promedio en el examen final de un curso de estadística fue 73 puntos. Este semestre una clase con 27 estudiantes utilizando un nuevo libro de texto obtuvo en promedio 78.1. Se sabe que la varianza poblacional es <span class="math inline">\(\sigma^2=49\)</span>. ¿Hay evidencia para afirmar que el nuevo libro de texto hizo que el resultado del examen final fuera más alto?. Use un nivel de significancia del 5 %</h4>
</div>
<div id="paso-1-los-datos-del-problema." class="section level4">
<h4><strong>Paso 1: Los datos del problema.</strong></h4>
</div>
<div id="barx78.1" class="section level4">
<h4><span class="math inline">\(\bar{X}=78.1\)</span></h4>
</div>
<div id="mu_0-73" class="section level4">
<h4><span class="math inline">\(\mu_0 = 73\)</span></h4>
</div>
<div id="n-27" class="section level4">
<h4><span class="math inline">\(n = 27\)</span></h4>
</div>
<div id="sigma-7" class="section level4">
<h4><span class="math inline">\(\sigma = 7\)</span></h4>
</div>
<div id="alpha-0.05" class="section level4">
<h4><span class="math inline">\(\alpha = 0.05\)</span></h4>
</div>
<div id="paso-2-plantear-las-hipotesis" class="section level4">
<h4><strong>Paso 2: Plantear las hipótesis</strong></h4>
</div>
<div id="h_0-mu-73" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 73\)</span></h4>
</div>
<div id="h_a-mu-73" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; 73\)</span></h4>
</div>
<div id="paso-3-estadistico-de-prueba-y-supuestos" class="section level4">
<h4><strong>Paso 3: Estadístico de prueba y supuestos</strong></h4>
</div>
<div id="los-supuestos-para-este-problema-son" class="section level4">
<h4>Los supuestos para este problema son:</h4>
<ol style="list-style-type: lower-alpha">
<li><h4 id="poblacion-normal">Población Normal</h4></li>
<li><h4 id="varianza-conocida-sigma">Varianza conocida <span class="math inline">\(\sigma\)</span></h4></li>
</ol>
</div>
<div id="el-estadistico-de-prueba-bajo-h_0-es" class="section level4">
<h4>El estadístico de prueba bajo <span class="math inline">\(H_0\)</span> es</h4>
</div>
<div id="zdfracbarx-mu_0sigmasqrtndfrac78.1-737sqrt272.91" class="section level4">
<h4><span class="math display">\[Z^*=\dfrac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}=\dfrac{78.1-73}{7/\sqrt{27}}=2.91\]</span></h4>
</div>
<div id="entonces-la-region-de-rechazo-esta-dada-por-todos-los-valores-de-z-mayores-que-2.91" class="section level4">
<h4>Entonces la región de rechazo está dada por todos los valores de <span class="math inline">\(Z\)</span> mayores que <span class="math inline">\(2.91\)</span></h4>
</div>
<div id="paso-4-valor-critico-y-region-de-rechazo" class="section level4">
<h4><strong>Paso 4: Valor crítico y región de rechazo</strong></h4>
</div>
<div id="para-calcular-el-valor-critico-de-la-distribucion-normal-estandar-se-usa-la-siguiente-funcion-en-rstudio.-como-la-prueba-es-a-cola-deracha-debemos-declara-lower.tail-false" class="section level4">
<h4>Para calcular el valor crítico de la distribución normal estándar se usa la siguiente función en <code>RStudio</code>. Como la prueba es a cola deracha debemos declara <code>lower.tail = FALSE</code></h4>
<pre class="r"><code>qnorm(0.05,lower.tail = FALSE)</code></pre>
<pre><code>## [1] 1.644854</code></pre>
</div>
<div id="entonces-tenemos-que" class="section level4">
<h4>Entonces tenemos que</h4>
</div>
<div id="z-z_0.05" class="section level4">
<h4><span class="math display">\[Z^* &gt; Z_{0.05}\]</span></h4>
</div>
<div id="es-decir" class="section level4">
<h4>es decir,</h4>
</div>
<div id="section" class="section level4">
<h4><span class="math display">\[2.914 &gt; 1.644\]</span></h4>
</div>
<div id="paso-5-decision-y-conclusion" class="section level4">
<h4><strong>Paso 5: Decisión y conclusión</strong></h4>
</div>
<div id="decision-se-decide-rechazar-la-hipotesis-nula-h_0-dado-a-que-z-z_0.05." class="section level4">
<h4><strong>Decisión</strong>: Se decide rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, dado a que <span class="math inline">\(Z^* &gt; Z_{0.05}\)</span>.</h4>
</div>
<div id="conclusion-se-encontro-evidencia-significativa-de-que-la-nota-final-aumento-con-el-uso-del-nuevo-libro-de-texto-en-la-clase." class="section level4">
<h4><strong>Conclusión</strong>: Se encontró evidencia significativa de que la nota final aumentó con el uso del nuevo libro de texto en la clase.</h4>
</div>
</div>
<div id="p---values" class="section level3">
<h3>p - values</h3>
<div id="es-frecuente-que-en-articulos-cientificos-lo-que-se-reporte-es-el-p-value-de-la-prueba-de-hipotesis-de-manera-que-el-lector-pueda-llegar-a-sus-propias-conclusiones." class="section level4">
<h4>Es frecuente que en artículos científicos lo que se reporte es el “p-value” de la prueba de hipótesis de manera que el lector pueda llegar a sus propias conclusiones.</h4>
<p><strong>El p-value es una probabilidad, y es la probabilidad de observar un valor igual o mayor al estadístico de prueba bajo el supuesto de que la hipótesis nula <span class="math inline">\(H_0\)</span> es cierta</strong>.</p>
</div>
<div id="un-p-value-pequeno-es-evidencia-en-contra-de-la-hipotesis-nula-y-a-favor-de-la-hipotesis-alterna.-cuando-el-nivel-de-significancia-alpha-ha-sido-seleccionado-la-hipotesis-nula-se-rechaza-si-el-p-value-es-menor-que-alpha." class="section level4">
<h4>Un p-value pequeño es evidencia en contra de la hipótesis nula y a favor de la hipótesis alterna. Cuando el nivel de significancia <span class="math inline">\(\alpha\)</span> ha sido seleccionado, la hipótesis nula se rechaza si el p-value es menor que <span class="math inline">\(\alpha\)</span>.</h4>
</div>
<div id="formulas-para-calcular-p-value-pero-depende-de-la-forma-de-la-hipotesis-alterna" class="section level4">
<h4>Fórmulas para calcular “p-value”: Pero depende de la forma de la hipótesis alterna</h4>
</div>
<div id="si-h_a-mu-mu_0-entonces-el-p-value-pz-z." class="section level4">
<h4>Si <span class="math inline">\(H_a: \mu &lt; \mu_0\)</span>, entonces el p-value = <span class="math inline">\(P(Z &lt; Z^*)\)</span>.</h4>
</div>
<div id="si-h_a-mu-mu_0-entonces-el-p-value-pz-z.-1" class="section level4">
<h4>Si <span class="math inline">\(H_a: \mu &gt; \mu_0\)</span>, entonces el p-value = <span class="math inline">\(P(Z &gt; Z^*)\)</span>.</h4>
</div>
<div id="si-h_a-mu-neq-mu_0-entonces-p-value-2pz-z." class="section level4">
<h4>Si <span class="math inline">\(H_a: \mu \neq \mu_0\)</span>, entonces p-value = <span class="math inline">\(2P(Z &gt; |Z^*|)\)</span>.</h4>
</div>
<div id="ejemplo-2.-en-estudios-previos-se-ha-determinado-que-el-nivel-de-colesterol-promedio-de-pacientes-con-problemas-cardiacos-es-220.-un-cardiologo-piensa-que-en-realidad-el-nivel-es-mas-alto-y-para-probar-su-afirmacion-usa-una-muestra-del-colesterol-en-20-pacientes.-habra-suficiente-evidencia-estadistica-para-apoyar-la-afirmacion-del-cardiologo-justificar-su-contestacion-basandose-en-el-p-value.-asuma-sigma13" class="section level4">
<h4>Ejemplo 2. En estudios previos se ha determinado que el nivel de colesterol promedio de pacientes con problemas cardíacos es 220. Un cardiólogo piensa que en realidad el nivel es más alto y para probar su afirmación usa una muestra del colesterol en 20 pacientes. ¿Habrá suficiente evidencia estadística para apoyar la afirmación del cardiólogo? Justificar su contestación basándose en el “p-value”. Asuma <span class="math inline">\(\sigma=13\)</span></h4>
</div>
<div id="los-datos-del-problema-son" class="section level4">
<h4>Los datos del problema son:</h4>
</div>
<div id="section-1" class="section level4">
<h4>217, 223, 225, 245, 238, 216, 217, 226, 202, 233, 235, 242, 219, 221, 234, 199, 236, 248, 218, 224</h4>
</div>
<div id="debemos-ingresar-los-datos-a-rstudio." class="section level4">
<h4>Debemos ingresar los datos a RStudio.</h4>
<pre class="r"><code>colesterol &lt;- c(217, 223, 225, 245, 238, 216, 217, 226, 202, 233, 235, 242, 219, 221, 234, 199, 236, 248, 218, 224)
mean(colesterol)</code></pre>
<pre><code>[1] 225.9</code></pre>
</div>
<div id="paso-1-los-datos-del-problema-y-supuestos-del-problema-son" class="section level4">
<h4><strong>Paso 1: Los datos del problema y supuestos del problema son</strong></h4>
</div>
<div id="barx225.9" class="section level4">
<h4><span class="math inline">\(\bar{X}=225.9\)</span></h4>
</div>
<div id="mu_0-220" class="section level4">
<h4><span class="math inline">\(\mu_0 = 220\)</span></h4>
</div>
<div id="n-20" class="section level4">
<h4><span class="math inline">\(n = 20\)</span></h4>
</div>
<div id="sigma-13" class="section level4">
<h4><span class="math inline">\(\sigma = 13\)</span></h4>
</div>
<div id="alpha-0.05-1" class="section level4">
<h4><span class="math inline">\(\alpha = 0.05\)</span></h4>
</div>
<div id="paso-2-plantear-las-hipotesis-1" class="section level4">
<h4><strong>Paso 2: Plantear las hipótesis</strong></h4>
</div>
<div id="h_0-mu-220" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 220\)</span></h4>
</div>
<div id="h_a-mu-220" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; 220\)</span></h4>
</div>
<div id="paso-3-estadistico-de-prueba" class="section level4">
<h4><strong>Paso 3: Estadístico de prueba</strong></h4>
</div>
<div id="el-estadistico-de-prueba-bajo-h_0-es-1" class="section level4">
<h4>El estadístico de prueba bajo <span class="math inline">\(H_0\)</span> es</h4>
</div>
<div id="zdfracbarx-mu_0sigmasqrtndfrac225.9---22013sqrt22dfrac5.92.9068882.029" class="section level4">
<h4><span class="math display">\[Z^*=\dfrac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}=\dfrac{225.9 - 220}{13/\sqrt{22}}=\dfrac{5.9}{2.906888}=2.029\]</span></h4>
</div>
<div id="entonces-la-region-de-rechazo-esta-dada-por-todos-los-valores-de-z-mayores-que-2.029" class="section level4">
<h4>Entonces la región de rechazo está dada por todos los valores de <span class="math inline">\(Z\)</span> mayores que <span class="math inline">\(2.029\)</span></h4>
</div>
<div id="paso-4-valor-critico-y-region-de-rechazo-1" class="section level4">
<h4><strong>Paso 4: Valor crítico y región de rechazo</strong></h4>
</div>
<div id="para-calcular-el-valor-critico-de-la-distribucion-normal-estandar-se-usa-la-siguiente-funcion-en-rstudio." class="section level4">
<h4>Para calcular el valor crítico de la distribución normal estándar se usa la siguiente función en <code>RStudio</code>.</h4>
<pre class="r"><code>qnorm(0.05, lower.tail = FALSE)</code></pre>
<pre><code>## [1] 1.644854</code></pre>
</div>
<div id="entonces-tenemos-que-1" class="section level4">
<h4>Entonces tenemos que</h4>
</div>
<div id="z-z_0.05-1" class="section level4">
<h4><span class="math display">\[Z^* &gt; Z_{0.05}\]</span></h4>
</div>
<div id="es-decir-1" class="section level4">
<h4>es decir,</h4>
</div>
<div id="section-2" class="section level4">
<h4><span class="math display">\[2.029 &gt; 1.644\]</span></h4>
</div>
<div id="paso-5-decision-y-conclusion-1" class="section level4">
<h4><strong>Paso 5: Decisión y conclusión</strong></h4>
</div>
<div id="decision-se-decide-rechazar-la-hipotesis-nula-h_0-dado-a-que-z-z_0.05-es-decir-2.914-1.644" class="section level4">
<h4><strong>Decisión</strong>: Se decide rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, dado a que <span class="math inline">\(Z^* &gt; Z_{0.05}\)</span>, es decir <span class="math inline">\(2.914 &gt; 1.644\)</span></h4>
</div>
<div id="conclusion-se-encontro-evidencia-significativa-de-que-la-nota-final-aumento-con-el-uso-del-nuevo-libro-de-texto-en-la-clase.-1" class="section level4">
<h4><strong>Conclusión</strong>: Se encontró evidencia significativa de que la nota final aumentó con el uso del nuevo libro de texto en la clase.</h4>
</div>
<div id="todo-el-procedimiento-anterior-es-correcto-pero-la-otra-forma-de-tomar-la-decision-de-rechazo-o-no-rechazo-suele-hacerse-basandose-en-el-p-value.-como-calculamos-el-p-value" class="section level4">
<h4>Todo el procedimiento anterior es correcto, pero la otra forma de tomar la decisión de rechazo o no rechazo, suele hacerse basándose en el “p-value”. ¿Cómo calculamos el “p-value”?</h4>
</div>
<div id="para-encontrar-el-p-value-debemos-calcular-la-siguiente-probabilidad-pz-z-es-decir-pz-2.029.-para-esto-usamos-rstudio." class="section level4">
<h4>Para encontrar el “p-value”, debemos calcular la siguiente probabilidad: <span class="math inline">\(P(Z &gt; Z^*)\)</span>, es decir <span class="math inline">\(P(Z &gt; 2.029)\)</span>. Para esto usamos RStudio.</h4>
<pre class="r"><code>1 - pnorm(2.029)</code></pre>
<pre><code>## [1] 0.02122915</code></pre>
</div>
<div id="decision-y-conclusion-usando-el-p-value" class="section level4">
<h4><strong>Decisión y conclusión usando el “p-value”</strong></h4>
</div>
<div id="el-valor-del-p-value-es-0.021-menor-que-el-nivel-de-significacion-alpha-.05-por-lo-tanto-se-rechaza-la-hipotesis-nula-y-se-concluye-de-que-si-hay-evidencia-estadistica-de-que-el-nivel-de-colesterol-promedio-de-los-pacientes-con-problemas-cardiacos-es-mayor-de-220.-o-sea-los-resultados-apoyan-lo-que-afirma-el-cardiologo." class="section level4">
<h4>El valor del “p-value” es <span class="math inline">\(0.021\)</span> menor que el nivel de significación <span class="math inline">\(\alpha =.05\)</span>, por lo tanto; se rechaza la hipótesis nula y se concluye de que sí hay evidencia estadística de que el nivel de colesterol promedio de los pacientes con problemas cardíacos es mayor de 220. O sea los resultados apoyan lo que afirma el cardiólogo.</h4>
<blockquote>
<p><strong>Caso 2: Varianza poblacional <span class="math inline">\(\sigma^2\)</span> es desconocida</strong></p>
</blockquote>
</div>
<div id="en-este-caso-no-es-posible-usar-la-distribucion-normal-estandar-por-tanto-se-usa-la-distribucion-t-student." class="section level4">
<h4>En este caso no es posible usar la distribución normal estándar, por tanto se usa la distribución t-student.</h4>
</div>
<div id="el-estadistico-de-prueba-bajo-h_0-es-2" class="section level4">
<h4>El estadístico de prueba bajo <span class="math inline">\(H_0\)</span> es</h4>
</div>
<div id="tdfracbarx-mu_0ssqrtn" class="section level4">
<h4><span class="math display">\[t^*=\dfrac{\bar{X}-\mu_0}{s/\sqrt{n}}\]</span></h4>
</div>
<div id="y-el-valor-critico-de-la-distribucion-t-student-sera-t_alphan-1-donde-n-1-son-los-grados-de-libertad." class="section level4">
<h4>y el valor crítico de la distribución t-student será <span class="math inline">\(t_{\alpha,n-1}\)</span>, donde <span class="math inline">\(n-1\)</span> son los grados de libertad.</h4>
</div>
<div id="si-la-prueba-es-a-cola-izquierda-la-region-de-rechazo-son-los-valores-de-t--t_alpha-y-se-decide-rechazar-h_0-si-t--t_alpha." class="section level4">
<h4>Si la prueba es a cola izquierda la región de rechazo son los valores de <span class="math inline">\(t &lt; -t_{\alpha}\)</span>, y se decide rechazar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(t^* &lt; -t_{\alpha}\)</span>.</h4>
</div>
<div id="si-la-prueba-es-a-cola-derecha-la-region-de-rechazo-son-los-valores-de-t-t_alpha-y-se-decide-rechazar-h_0-si-t-t_alpha." class="section level4">
<h4>Si la prueba es a cola derecha la región de rechazo son los valores de <span class="math inline">\(t &gt; t_{\alpha}\)</span>, y se decide rechazar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(t^* &gt; t_{\alpha}\)</span>.</h4>
</div>
<div id="si-la-prueba-es-a-dos-colas-la-region-de-rechazo-son-los-valores-de-t--t_alpha-y-los-valores-de-t-t_alpha-y-se-decide-rechazar-h_0-si-t-t_alpha." class="section level4">
<h4>Si la prueba es a dos colas la región de rechazo son los valores de <span class="math inline">\(t &lt; -t_{\alpha}\)</span> y los valores de <span class="math inline">\(t &gt; t_{\alpha}\)</span>, y se decide rechazar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(|t^*| &gt; t_{\alpha}\)</span>.</h4>
<div class="figure">
<img src="test-t.jpg" />

</div>
<blockquote>
<p>Ejemplos</p>
</blockquote>
</div>
<div id="las-ventas-diarias-actuales-de-cafe-molido-regular-en-un-supermercado-son-en-promedio-de-55-libras-y-varian-segun-una-distribucion-normal.-la-tienda-quiere-reducir-el-precio-para-vender-intentar-vender-mas-cafe-molido.-despues-de-la-reduccion-de-precios-las-ventas-en-las-proximas-tres-semanas-promediaron-63-libras-con-una-desviacion-estandar-de-15.-es-esto-una-buena-evidencia-de-que-las-ventas-promedio-son-ahora-de-360-libras-construya-un-intervalo-de-confianza-del-90-para-responder-a-la-pregunta." class="section level4">
<h4>1. Las ventas diarias actuales de café molido regular en un supermercado son en promedio de 55 libras, y varían según una distribución normal. La tienda quiere reducir el precio para vender intentar vender más café molido. Después de la reducción de precios, las ventas en las próximas tres semanas promediaron 63 libras, con una desviación estándar de 15. ¿Es esto una buena evidencia de que las ventas promedio son ahora de 360 libras? Construya un intervalo de confianza del 90 % para responder a la pregunta.</h4>
</div>
<div id="paso-1-los-datos-del-problema" class="section level4">
<h4><strong>Paso 1: Los datos del problema</strong></h4>
</div>
<div id="barx55" class="section level4">
<h4><span class="math inline">\(\bar{X}=55\)</span></h4>
</div>
<div id="mu-63" class="section level4">
<h4><span class="math inline">\(\mu = 63\)</span></h4>
</div>
<div id="n-43" class="section level4">
<h4><span class="math inline">\(n = 43\)</span></h4>
</div>
<div id="s-18" class="section level4">
<h4><span class="math inline">\(S = 18\)</span></h4>
</div>
<div id="alpha-0.1" class="section level4">
<h4><span class="math inline">\(\alpha = 0.1\)</span></h4>
</div>
<div id="paso-2-plantear-las-hipotesis-2" class="section level4">
<h4><strong>Paso 2: Plantear las hipótesis</strong></h4>
</div>
<div id="h_0-mu-55" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 55\)</span></h4>
</div>
<div id="h_a-mu-55" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; 55\)</span></h4>
</div>
<div id="paso-3-estadistico-de-prueba-y-supuestos-1" class="section level4">
<h4><strong>Paso 3: Estadístico de prueba y supuestos</strong></h4>
</div>
<div id="se-asume-que" class="section level4">
<h4>Se asume que:</h4>
<ol style="list-style-type: lower-alpha">
<li><h4 id="los-datos-provienen-de-una-distribucion-normal.">Los datos provienen de una distribución normal.</h4></li>
<li><h4 id="la-varianza-sigma-es-desconocida.">La varianza <span class="math inline">\(\sigma\)</span> es desconocida.</h4></li>
</ol>
</div>
<div id="el-estadistico-de-prueba-bajo-h_0-es-3" class="section level4">
<h4>El estadístico de prueba bajo <span class="math inline">\(H_0\)</span> es</h4>
</div>
<div id="t-dfracbarx-mu_0ssqrtndfrac63-5518sqrt432.914" class="section level4">
<h4><span class="math display">\[t^* =\dfrac{\bar{X}-\mu_0}{S/\sqrt{n}}=\dfrac{63-55}{18/\sqrt{43}}=2.914\]</span></h4>
</div>
<div id="entonces-la-region-de-rechazo-esta-dada-por-todos-los-valores-de-t_alpha-mayores-que-2.91" class="section level4">
<h4>Entonces la región de rechazo está dada por todos los valores de <span class="math inline">\(t_{\alpha}\)</span> mayores que <span class="math inline">\(2.91\)</span></h4>
</div>
<div id="paso-4-valor-critico" class="section level4">
<h4><strong>Paso 4: Valor crítico</strong></h4>
</div>
<div id="para-calcular-el-valor-critico-de-la-distribucion-t-student-con-n-1-grados-de-libertad-es-decir-con-43-142-se-usa-la-siguiente-funcion-en-rstudio" class="section level4">
<h4>Para calcular el valor crítico de la distribución t-student con <span class="math inline">\(n-1\)</span> grados de libertad, es decir con 43-1=42 se usa la siguiente función en <code>RStudio</code></h4>
<pre class="r"><code>qt(0.1,42,lower.tail = FALSE)</code></pre>
<pre><code>## [1] 1.302035</code></pre>
</div>
<div id="entonces-tenemos-que-2" class="section level4">
<h4>Entonces tenemos que</h4>
</div>
<div id="t-t_0.143" class="section level4">
<h4><span class="math display">\[t^* &lt; t_{0.1,43}\]</span></h4>
</div>
<div id="es-decir-2" class="section level4">
<h4>es decir,</h4>
</div>
<div id="section-3" class="section level4">
<h4><span class="math display">\[2.914 &gt; 1.302\]</span></h4>
</div>
<div id="paso-5-decision-y-conclusion-2" class="section level4">
<h4><strong>Paso 5: Decisión y conclusión</strong></h4>
</div>
<div id="decision-se-decide-rechazar-la-hipotesis-nula-h_0-dado-a-que-t-t_0.142." class="section level4">
<h4><strong>Decisión</strong>: Se decide rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, dado a que <span class="math inline">\(t^* &gt; t_{0.1,42}\)</span>.</h4>
</div>
<div id="conclusion-se-encontro-evidencia-significativa-de-que-las-ventas-aumentaron-y-que-por-tanto-la-promocion-fue-exitosa." class="section level4">
<h4><strong>Conclusión</strong>: Se encontró evidencia significativa de que las ventas aumentaron y que por tanto la promoción fue exitosa.</h4>
</div>
</div>
<div id="prueba-de-hipotesis-para-una-proporcion" class="section level3">
<h3>Prueba de hipótesis para una proporción</h3>
<div id="para-la-proporcion-poblacional-donde-p_0-es-un-numero-fijo-definido-por-el-investigador-las-hipotesis-se-pueden-definir-de-una-de-las-tres-formas-siguientes" class="section level4">
<h4>Para la proporción poblacional, donde <span class="math inline">\(p_0\)</span> es un número fijo definido por el investigador, las hipótesis se pueden definir de una de las tres formas siguientes:</h4>
</div>
<div id="prueba-a-cola-izquierda-2" class="section level4">
<h4>1. Prueba a cola izquierda:</h4>
</div>
<div id="h_0-p-p_0" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = p_0\)</span></h4>
</div>
<div id="h_a-p-p_0" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &lt; p_0\)</span></h4>
</div>
<div id="prueba-a-cola-derecha-2" class="section level4">
<h4>2. Prueba a cola derecha:</h4>
</div>
<div id="h_0-p-_0" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = _0\)</span></h4>
</div>
<div id="h_a-p-p_0-1" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &gt; p_0\)</span></h4>
</div>
<div id="prueba-a-dos-colas-2" class="section level4">
<h4>3. Prueba a dos colas:</h4>
</div>
<div id="h_0-p-p_0-1" class="section level4">
<h4><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = p_0\)</span></h4>
</div>
<div id="h_a-p-neq-p_0" class="section level4">
<h4><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p \neq p_0\)</span></h4>
</div>
<div id="la-distribucion-del-estadistico-de-prueba-bajo-la-hipotesis-nula-h_0-p-p_0-es" class="section level4">
<h4>La distribución del estadístico de prueba bajo la hipótesis nula <span class="math inline">\(H_0 : p= p_0\)</span> es:</h4>
</div>
<div id="zdfrachatp-p_0sqrtdfracp_01-p_0n" class="section level4">
<h4><span class="math display">\[Z^*=\dfrac{\hat{p}-p_0}{\sqrt{\dfrac{p_0(1-p_0)}{n}}}\]</span></h4>
<div class="figure">
<img src="proportion.jpg" />

</div>
</div>
<div id="supuestos" class="section level4">
<h4>SUPUESTOS:</h4>
</div>
<div id="este-metodo-tiene-los-siguientes-supuestos" class="section level4">
<h4>Este método tiene los siguientes supuestos:</h4>
</div>
<div id="i-np-geq-10" class="section level4">
<h4>i) <span class="math inline">\(np \geq 10\)</span></h4>
</div>
<div id="ii-n1-p-geq-10" class="section level4">
<h4>ii) <span class="math inline">\(n(1-p) \geq 10\)</span></h4>
<blockquote>
<p>Ejemplos</p>
</blockquote>
</div>
<div id="un-fabricante-de-refrescos-afirma-que-la-mayoria-de-los-adultos-prefieren-su-bebida-lider-en-comparacion-con-la-de-su-principal-competidor.-para-probar-esta-afirmacion-500-personas-seleccionadas-aleatoriamente-recibieron-las-dos-bebidas-en-orden-aleatorio-para-degustar.-entre-ellos-270-preferian-la-marca-del-fabricante-de-refrescos-211-preferian-la-marca-del-competidor-y-19-no-podian-decidirse.-determine-si-hay-evidencia-suficiente-al-nivel-de-significancia-del-5-para-respaldar-el-reclamo-del-fabricante-de-refrescos-de-que-la-poblacion-esta-dividida-en-partes-iguales-en-su-preferencia." class="section level4">
<h4>1. Un fabricante de refrescos afirma que la mayoría de los adultos prefieren su bebida líder en comparación con la de su principal competidor. Para probar esta afirmación, 500 personas seleccionadas aleatoriamente recibieron las dos bebidas en orden aleatorio para degustar. Entre ellos, 270 preferían la marca del fabricante de refrescos, 211 preferían la marca del competidor y 19 no podían decidirse. Determine si hay evidencia suficiente, al nivel de significancia del 5%, para respaldar el reclamo del fabricante de refrescos de que la población está dividida en partes iguales en su preferencia.</h4>
</div>
<div id="paso-1-los-datos-del-problema-y-supuestos-del-problema-son-1" class="section level4">
<h4><strong>Paso 1: Los datos del problema y supuestos del problema son</strong></h4>
</div>
<div id="hatp2705000.54" class="section level4">
<h4><span class="math inline">\(\hat{p}=270/500=0.54\)</span></h4>
</div>
<div id="p_0-0.5" class="section level4">
<h4><span class="math inline">\(p_0 = 0.5\)</span></h4>
<p><span class="math inline">\(n = 500\)</span></p>
<p><span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Paso 2: Plantear las hipótesis</strong></p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.5\)</span></p>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &gt; 0.5\)</span></p>
<p><strong>Paso 3: Estadístico de prueba y supuestos</strong></p>
</div>
<div id="este-metodo-tiene-los-siguientes-supuestos-1" class="section level4">
<h4>Este método tiene los siguientes supuestos:</h4>
</div>
<div id="i-np-geq-10-1" class="section level4">
<h4>i) <span class="math inline">\(np \geq 10\)</span></h4>
</div>
<div id="ii-n1-p-geq-10-1" class="section level4">
<h4>ii) <span class="math inline">\(n(1-p) \geq 10\)</span></h4>
</div>
<div id="el-estadistico-de-prueba-bajo-h_0-es-4" class="section level4">
<h4>El estadístico de prueba bajo <span class="math inline">\(H_0\)</span> es</h4>
</div>
<div id="zdfrachatp-p_0sqrtdfracp_01-p_0ndfrac0.54-0.5sqrtdfrac0.51-0.55001.789" class="section level4">
<h4><span class="math display">\[Z^*=\dfrac{\hat{p}-p_0}{\sqrt{\dfrac{p_0(1-p_0)}{n}}}=\dfrac{0.54-0.5}{\sqrt{\dfrac{0.5(1-0.5)}{500}}}=1.789\]</span></h4>
</div>
<div id="entonces-la-region-de-rechazo-esta-dada-por-todos-los-valores-de-z_alpha-mayores-que-1.789" class="section level4">
<h4>Entonces la región de rechazo está dada por todos los valores de <span class="math inline">\(Z_{\alpha}\)</span> mayores que <span class="math inline">\(1.789\)</span></h4>
</div>
<div id="paso-4-valor-critico-1" class="section level4">
<h4><strong>Paso 4: Valor crítico</strong></h4>
</div>
<div id="para-calcular-el-valor-critico-de-la-distribucion-normal-estandar-usamos-la-siguiente-funcion-en-rstudio." class="section level4">
<h4>Para calcular el valor crítico de la distribución normal estándar usamos la siguiente función en <code>RStudio</code>.</h4>
<pre class="r"><code>qnorm(0.05, lower.tail = FALSE)</code></pre>
<pre><code>## [1] 1.644854</code></pre>
</div>
<div id="entonces-tenemos-que-3" class="section level4">
<h4>Entonces tenemos que</h4>
</div>
<div id="z-z_0.05-2" class="section level4">
<h4><span class="math display">\[Z^* &gt; Z_{0.05}\]</span></h4>
</div>
<div id="es-decir-3" class="section level4">
<h4>es decir,</h4>
</div>
<div id="section-4" class="section level4">
<h4><span class="math display">\[1.789 &gt; 1.644\]</span></h4>
</div>
<div id="paso-5-decision-y-conclusion-3" class="section level4">
<h4><strong>Paso 5: Decisión y conclusión</strong></h4>
</div>
<div id="decision-se-decide-rechazar-la-hipotesis-nula-h_0-dado-a-que-z-z.05." class="section level4">
<h4><strong>Decisión</strong>: Se decide rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>, dado a que <span class="math inline">\(Z^* &gt; {Z^*.05}\)</span>.</h4>
</div>
<div id="conclusion-se-encontro-evidencia-significativa-de-que-los-adultos-prefieren-el-refresco-del-fabricante-uno." class="section level4">
<h4><strong>Conclusión</strong>: Se encontró evidencia significativa de que los adultos prefieren el refresco del fabricante uno.</h4>
</div>
<div id="los-bebes-recien-nacidos-son-mas-propensos-a-ser-ninos-que-ninas.-una-muestra-aleatoria-encontro-13173-ninos-nacidos-entre-25468-recien-nacidos.-hay-evidencia-de-que-el-nacimiento-de-ninos-es-mas-comun-que-el-nacimiento-de-ninas-en-toda-la-poblacion-use-alpha0.1." class="section level4">
<h4>2. Los bebés recién nacidos son más propensos a ser niños que niñas. Una muestra aleatoria encontró 13173 niños nacidos entre 25468 recién nacidos. ¿Hay evidencia de que el nacimiento de niños es más común que el nacimiento de niñas en toda la población? Use <span class="math inline">\(\alpha=0.1\)</span>.</h4>
</div>
</div>
</div>
<div id="pruebas-de-hipotesis-con-rstudio." class="section level2">
<h2>Pruebas de hipótesis con RStudio.</h2>
<p>Podemos usar <code>RStudio</code> para llevar a cabo pruebas de hipótesis, tanto para la media con <span class="math inline">\(\sigma\)</span> conocida o <span class="math inline">\(\sigma\)</span> desconocida. Al igual que para proporciones poblacionales.</p>
<div id="pruebas-de-hipotesis-para-la-media-poblacional-mu-usando-rstudio" class="section level3">
<h3>Pruebas de hipótesis para la media poblacional <span class="math inline">\(\mu\)</span> usando <code>RStudio</code></h3>
</div>
<div id="caso-1-prueba-de-hipotesis-para-mu-con-sigma-conocida" class="section level3">
<h3><strong>Caso 1: Prueba de hipótesis para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma\)</span> conocida</strong></h3>
<div id="para-este-caso-podemos-usar-la-funcion-z.test-disponible-en-el-paquete-bsda.-la-funcion-z.test-tiene-los-siguientes-argumentos" class="section level4">
<h4>Para este caso podemos usar la función <code>z.test()</code> disponible en el paquete <code>BSDA</code>. La función <code>z.test()</code> tiene los siguientes argumentos:</h4>
<p><code>z.test(x, alternative = &quot;two.sided&quot;, mu = 0, sigma.x = NULL, conf.level = 0.95)</code></p>
</div>
<div id="el-vector-de-datos-x." class="section level4">
<h4>1. El vector de datos <code>x</code>.</h4>
</div>
<div id="para-alternative-por-defecto-viene-con-two.sided-prueba-a-dos-colas.-se-puede-cambiar-por-greater-prueba-a-cola-derecha-o-less-prueba-a-cola-izquierda." class="section level4">
<h4>2. Para <code>alternative</code> por defecto viene con <code>&quot;two.sided&quot;</code> (prueba a dos colas). Se puede cambiar por <code>&quot;greater&quot;</code> (prueba a cola derecha) o <code>&quot;less&quot;</code> (prueba a cola izquierda).</h4>
</div>
<div id="el-valor-para-sigma-sigma.x" class="section level4">
<h4>3. El valor para <span class="math inline">\(\sigma\)</span> <code>sigma.x</code></h4>
</div>
<div id="el-valor-para-mu_0-se-ingresa-en-mu-que-por-defecto-viene-mu0.-usted-debe-cambiarlo." class="section level4">
<h4>4. El valor para <span class="math inline">\(\mu_0\)</span>, se ingresa en <code>mu</code>, que por defecto viene <code>mu=0</code>. Usted debe cambiarlo.</h4>
</div>
<div id="el-nivel-de-confianza-conf.level-viene-por-defecto-con-el-95-.-usted-lo-puede-cambiar." class="section level4">
<h4>5. El nivel de confianza <code>conf.level</code>, viene por defecto con el 95 %. Usted lo puede cambiar.</h4>
<blockquote>
<p>Ejemplo:</p>
</blockquote>
</div>
<div id="en-el-pasado-la-compra-promedio-de-un-cliente-en-una-tienda-determinada-era-de-55.-la-tienda-decide-publicar-un-anuncio-en-el-periodico-y-quiere-saber-si-esa-estrategia-publicitaria-lograra-aumentar-las-ventas.-en-la-semana-siguiente-al-anuncio-35-clientes-hicieron-compras-por-los-siguientes-montos-de-dinero" class="section level4">
<h4>1. En el pasado, la compra promedio de un cliente en una tienda determinada era de $55. La tienda decide publicar un anuncio en el periódico y quiere saber si esa estrategia publicitaria logrará aumentar las ventas. En la semana siguiente al anuncio, 35 clientes hicieron compras por los siguientes montos de dinero:</h4>
<pre><code> [1]  36.35  91.39  45.78  46.44  27.04  58.10  57.32  51.69  61.08  70.70
[11]  49.00  39.71  48.97  63.22  60.26  50.34  84.40  69.13  72.13  57.72
[21]  67.03  99.13  81.22  57.56  44.55  58.19  59.42  65.36  65.62  69.52
[31]  75.13 100.30  53.26  43.73  56.30</code></pre>
</div>
<div id="pruebe-a-un-nivel-de-significancia-del-10-si-la-promocion-en-realidad-fue-exitosa-asumiendo-que-se-conoce-sigma15." class="section level4">
<h4>Pruebe a un nivel de significancia del 10 % si la promoción en realidad fue exitosa, asumiendo que se conoce <span class="math inline">\(\sigma=15\)</span>.</h4>
</div>
<div id="las-respectivas-hipotesis-son" class="section level4">
<h4>Las respectivas hipotesis son:</h4>
</div>
<div id="h_0mu55." class="section level4">
<h4><span class="math inline">\(H_0:\mu=55\)</span>.</h4>
</div>
<div id="h_amu-55." class="section level4">
<h4><span class="math inline">\(H_a:\mu &gt; 55\)</span>.</h4>
</div>
<div id="entonces-tenemos-una-prueba-a-cola-derecha-greater-con-una-significancia-del-10-es-decir-alpha0.10." class="section level4">
<h4>Entonces tenemos una prueba a cola derecha (<code>greater</code>), con una significancia del 10 %, es decir <span class="math inline">\(\alpha=0.10\)</span>.</h4>
</div>
<div id="primero-debemos-ingresar-los-datos-a-rstudio." class="section level4">
<h4>Primero debemos ingresar los datos a RStudio.</h4>
<pre class="r"><code>ventas &lt;- c(36.35, 91.39, 45.78, 46.44, 27.04, 58.10, 57.32, 51.69, 61.08, 70.70, 49.00, 39.71, 48.97, 63.22, 60.26, 50.34, 84.40, 69.13, 72.13, 57.72, 67.03, 99.13, 81.22, 57.56, 44.55, 58.19, 59.42, 65.36, 65.62, 69.52, 75.13, 100.30, 53.26, 43.73, 56.30)</code></pre>
</div>
<div id="el-siguiente-codigo-ilustra-como-hacer-la-prueba-de-hipotesis-usando-rstudio-y-la-funcion-z.test-del-paquete-bsda." class="section level4">
<h4>El siguiente código ilustra cómo hacer la prueba de hipótesis usando RStudio y la función <code>z.test()</code> del paquete <code>BSDA</code>.</h4>
<pre class="r"><code>library(BSDA)
z.test(ventas, alternative = &quot;greater&quot;, mu = 55, sigma.x = 15, conf.level = 0.90)</code></pre>
<pre><code>
    One-sample z-Test

data:  ventas
z = 2.39, p-value = 0.008425
alternative hypothesis: true mean is greater than 55
90 percent confidence interval:
 57.81039       NA
sample estimates:
mean of x 
 61.05971 </code></pre>
</div>
<div id="comentarios-sobre-la-salida-de-r" class="section level4">
<h4><strong>Comentarios sobre la salida de R</strong></h4>
<div class="alert alert-info">
<p><strong>Importante!</strong> De la anterior salida podemos identificar la siguiente información:</p>
</div>
<p class="comment">
El valor del estadístico de prueba es <span class="math inline">\(Z^* = 2.39\)</span>
</p>
<p class="comment">
El p-value es <span class="math inline">\(0.008425\)</span>
</p>
<p class="comment">
La información de la salida dice que:<code>true mean is greater than 55</code>. Entonces <span class="math inline">\(\mu_0\)</span>, es <span class="math inline">\(55\)</span>. Por tanto las hipótesis respectivas fueron: <span class="math display">\[H_0:\mu=55\]</span> <span class="math display">\[H_a:\mu &gt; 55\]</span>
</p>
<p class="comment">
La significancia es del 10 %, es decir <span class="math inline">\(\alpha = 0.10\)</span>
</p>
<p class="comment">
La media estimada es <span class="math inline">\(\bar{X}=61.059\)</span>
</p>
</div>
<div id="conclusion-y-decision" class="section level4">
<h4><strong>Conclusión y decisión:</strong></h4>
</div>
<div id="decision-como-el-p-value-es-menor-que-alpha-0.008425-0.10.-la-decision-es-rechazar-la-hipotesis-nula-h_0." class="section level4">
<h4><strong>Decisión:</strong> Como el “p-value” es menor que <span class="math inline">\(\alpha\)</span> (0.008425 &lt; 0.10). La decisión es rechazar la hipotesis nula <span class="math inline">\(H_0\)</span>.</h4>
</div>
<div id="conclusion-la-media-de-las-ventas-es-mas-alta-que-antes-por-lo-tanto-el-anuncio-publicitario-funciono." class="section level4">
<h4><strong>Conclusión:</strong> La media de las ventas es más alta que antes, por lo tanto el anuncio publicitario funcionó.</h4>
</div>
</div>
<div id="caso-2-intervalo-para-mu-con-sigma-desconocida" class="section level3">
<h3><strong>Caso 2: Intervalo para <span class="math inline">\(\mu\)</span> con <span class="math inline">\(\sigma\)</span> desconocida</strong></h3>
<div id="recuerde-que-en-este-caso-ya-no-es-posible-usar-la-distribucion-normal-estandar-z-y-es-necesario-usar-la-t---student." class="section level4">
<h4>Recuerde que en este caso ya no es posible usar la distribución normal estándar <span class="math inline">\(Z\)</span>, y es necesario usar la t - Student.</h4>
</div>
<div id="para-este-caso-podemos-usar-la-funcion-t.test-disponible-en-la-base-de-r.-no-es-necesario-instalar-ningun-paquete.-.-la-funcion-t.test-tiene-los-siguientes-argumentos-t.testx-alternative-two.sided-mu-0-conf.level-0.95" class="section level4">
<h4>Para este caso podemos usar la función <code>t.test()</code> disponible en la base de R. (No es necesario instalar ningún paquete). . La función <code>t.test()</code> tiene los siguientes argumentos: <code>t.test(x, alternative = &quot;two.sided&quot;, mu = 0, conf.level = 0.95)</code></h4>
</div>
<div id="el-vector-de-datos-x.-1" class="section level4">
<h4>1. El vector de datos <code>x</code>.</h4>
</div>
<div id="para-alternative-por-defecto-viene-con-two.sided-prueba-a-dos-colas.-se-puede-cambiar-por-greater-prueba-a-cola-derecha-o-less-prueba-a-cola-izquierda.-1" class="section level4">
<h4>2. Para <code>alternative</code> por defecto viene con <code>&quot;two.sided&quot;</code> (prueba a dos colas). Se puede cambiar por <code>&quot;greater&quot;</code> (prueba a cola derecha) o <code>&quot;less&quot;</code> (prueba a cola izquierda).</h4>
</div>
<div id="el-valor-para-mu_0-se-ingresa-en-mu-que-por-defecto-viene-mu0.-usted-debe-cambiarlo.-1" class="section level4">
<h4>3. El valor para <span class="math inline">\(\mu_0\)</span>, se ingresa en <code>mu</code>, que por defecto viene <code>mu=0</code>. Usted debe cambiarlo.</h4>
</div>
<div id="el-nivel-de-confianza-conf.level-viene-por-defecto-con-el-95-.-usted-lo-puede-cambiar.-1" class="section level4">
<h4>4. El nivel de confianza <code>conf.level</code>, viene por defecto con el 95 %. Usted lo puede cambiar.</h4>
<blockquote>
<p>Ejemplo:</p>
</blockquote>
</div>
<div id="resolvamos-el-siguiente-ejercicio" class="section level4">
<h4>Resolvamos el siguiente ejercicio:</h4>
</div>
<div id="una-compania-afirma-que-sus-bocadillos-de-comida-contienen-un-promedio-de-28-g-de-azucar-por-porcion.-un-investigador-cree-que-la-empresa-esta-mintiendo-y-toma-una-muestra-aleatoria-de-15-porciones-de-bocadillos-y-encuentra-los-siguientes-datos-para-la-cantidad-de-azucar-por-porcion" class="section level4">
<h4>Una compañía afirma que sus bocadillos de comida contienen un promedio de 28 g de azúcar por porción. Un investigador cree que la empresa está mintiendo, y toma una muestra aleatoria de 15 porciones de bocadillos y encuentra los siguientes datos para la cantidad de azucar por porción:</h4>
<pre><code> [1] 27 28 31 28 28 31 29 25 27 27 30 29 29 28 27</code></pre>
</div>
<div id="realice-una-prueba-de-hipotesis-para-determinar-si-la-reclamacion-de-la-compania-es-valida-bajo-una-significancia-estadistica-del-5-." class="section level4">
<h4>Realice una prueba de hipótesis para determinar si la reclamación de la compañía es válida bajo una significancia estadística del 5 %.</h4>
<pre class="r"><code>azucar &lt;- c(27, 28, 31, 28, 28, 31, 29, 25, 27, 27, 30, 29, 29, 28, 27)</code></pre>
</div>
<div id="la-forma-de-usar-la-funcion-t.test-es-la-siguiente" class="section level4">
<h4>La forma de usar la función <code>t.test()</code> es la siguiente:</h4>
<pre class="r"><code>t.test(x = azucar, alternative = &quot;two.sided&quot;, mu = 28, conf.level = 0.95)</code></pre>
<pre><code>
    One Sample t-test

data:  azucar
t = 0.63587, df = 14, p-value = 0.5351
alternative hypothesis: true mean is not equal to 28
95 percent confidence interval:
 27.36720 29.16613
sample estimates:
mean of x 
 28.26667 </code></pre>
</div>
<div id="comentarios-sobre-la-salida-de-r-1" class="section level4">
<h4><strong>Comentarios sobre la salida de R</strong></h4>
<div class="alert alert-info">
<p><strong>Importante!</strong> De la anterior salida podemos identificar la siguiente información:</p>
</div>
<p class="comment">
Los grados de libertad <strong>(df)</strong> de la distribución t-Student fueron 14. Esto quiere decir que se usó una muestra de tamaño 15.
</p>
<p class="comment">
El valor del estadístico de prueba es <span class="math inline">\(t^* = 0.63587\)</span>
</p>
<p class="comment">
El p-value es <span class="math inline">\(0.5351\)</span>
</p>
<p class="comment">
La información de la salida dice que <code>true mean is not equal to 28</code>. Entonces <span class="math inline">\(\mu_0\)</span>, es <span class="math inline">\(28\)</span>. Por tanto las hipótesis respectivas fueron: <span class="math display">\[H_0:\mu=28\]</span> <span class="math display">\[H_a:\mu \neq 28\]</span>
</p>
<p class="comment">
La significancia es del 5 %, es decir <span class="math inline">\(\alpha = 0.05\)</span>
</p>
<p class="comment">
La media estimada es <span class="math inline">\(\bar{X}=28.2666\)</span>
</p>
</div>
<div id="conclusion-y-decision-1" class="section level4">
<h4><strong>Conclusión y decisión:</strong></h4>
</div>
<div id="decision-como-el-p-value-no-es-menor-que-alpha-es-decir-0.5351-0.05.-la-decision-es-no-rechazar-la-hipotesis-nula-h_0-dado-que-no-se-encontro-suficiente-evidencia-estadistica-para-hacerlo." class="section level4">
<h4><strong>Decisión:</strong> Como el “p-value” no es menor que <span class="math inline">\(\alpha\)</span>, es decir 0.5351 &gt; 0.05. La decisión es NO rechazar la hipotesis nula <span class="math inline">\(H_0\)</span>, dado que no se encontró suficiente evidencia estadística para hacerlo.</h4>
</div>
<div id="conclusion-la-empresa-esta-en-lo-correcto-al-afirmar-que-sus-bocadillos-tienen-en-promedio-28-g-de-azucar." class="section level4">
<h4><strong>Conclusión:</strong> La empresa esta en lo correcto al afirmar que sus bocadillos tienen en promedio 28 g de azucar.</h4>
</div>
</div>
<div id="pruebas-de-hipotesis-para-la-proporcion-poblacional-p-usando-rstudio" class="section level3">
<h3>Pruebas de hipotesis para la proporción poblacional <span class="math inline">\(p\)</span> usando <code>RStudio</code></h3>
<div id="tambien-podemos-realizar-pruebas-de-hipotesis-para-p.-la-funcion-prop.test-nos-puede-ayudar-en-esta-tarea." class="section level4">
<h4>También podemos realizar pruebas de hipotesis para <span class="math inline">\(p\)</span>. La función <code>prop.test()</code> nos puede ayudar en esta tarea.</h4>
</div>
<div id="x-es-el-numero-de-exitos." class="section level4">
<h4>1. <code>x</code> es el número de éxitos.</h4>
</div>
<div id="n-el-tamano-de-la-muestra-o-numero-de-ensayos-independientes." class="section level4">
<h4>2. <code>n</code> el tamaño de la muestra o número de ensayos independientes.</h4>
</div>
<div id="el-valor-para-p_0-se-ingresa-en-p-que-por-defecto-viene-p0.5.-usted-debe-cambiarlo-si-es-necesario." class="section level4">
<h4>3. El valor para <span class="math inline">\(p_0\)</span>, se ingresa en <code>p</code>, que por defecto viene <code>p=0.5</code>. Usted debe cambiarlo si es necesario.</h4>
</div>
<div id="para-alternative-por-defecto-viene-con-two.sided-prueba-a-dos-colas.-se-puede-cambiar-por-greater-prueba-a-cola-derecha-o-less-prueba-a-cola-izquierda.-2" class="section level4">
<h4>4. Para <code>alternative</code> por defecto viene con <code>&quot;two.sided&quot;</code> (prueba a dos colas). Se puede cambiar por <code>&quot;greater&quot;</code> (prueba a cola derecha) o <code>&quot;less&quot;</code> (prueba a cola izquierda).</h4>
</div>
<div id="el-nivel-de-confianza-conf.level-viene-por-defecto-con-el-95-.-usted-lo-puede-cambiar.-2" class="section level4">
<h4>5. El nivel de confianza <code>conf.level</code>, viene por defecto con el 95 %. Usted lo puede cambiar.</h4>
</div>
<div id="correct-true-es-el-factor-de-correccion-no-desactivar-si-n-es-pequeno." class="section level4">
<h4>6. <code>correct = TRUE</code> es el factor de corrección (No desactivar si n es pequeño.)</h4>
</div>
<div id="vamos-a-usar-prop.test-para-resolver-el-siguiente-problema" class="section level4">
<h4>Vamos a usar <code>prop.test()</code> para resolver el siguiente problema:</h4>
</div>
<div id="el-pew-research-center-informo-que-el-31.2-de-los-adultos-jovenes-de-18-a-34-anos-en-los-estados-unidos-vivian-con-sus-padres-en-2014.-un-gerente-de-una-empresa-de-bienes-raices-en-santa-barbara-california-piensa-que-la-tasa-de-adultos-jovenes-que-viven-con-sus-padres-es-menor-en-esa-ciudad.-de-una-muestra-aleatoria-de-125-adultos-jovenes-en-el-area-29-responden-que-viven-con-sus-padres.-compruebe-con-un-5-de-significancia-si-la-proporcion-de-adultos-jovenes-en-santa-barbara-que-viven-con-los-padres-es-menor-que-la-proporcion-en-todo-el-pais." class="section level4">
<h4>El Pew Research Center informó que el 31.2 % de los adultos jóvenes (de 18 a 34 años) en los Estados Unidos vivían con sus padres en 2014. Un gerente de una empresa de bienes raíces en Santa Bárbara, California, piensa que la tasa de adultos jóvenes que viven con sus padres es menor en esa ciudad. De una muestra aleatoria de 125 adultos jóvenes en el área, 29 responden que viven con sus padres. Compruebe con un 5 % de significancia si la proporción de adultos jóvenes en Santa Bárbara que viven con los padres es menor que la proporción en todo el país.</h4>
</div>
<div id="entonces-tenemos-que-n125-x29.-entonces-usando-prop.test-tenemos" class="section level4">
<h4>Entonces tenemos que <span class="math inline">\(n=125\)</span>, <span class="math inline">\(X=29\)</span>. Entonces usando <code>prop.test()</code> tenemos:</h4>
<pre class="r"><code>prop.test(x = 29, n=125, alternative = &quot;less&quot;,p = 0.312, conf.level = 0.95, correct = TRUE)</code></pre>
<pre><code>
    1-sample proportions test with continuity correction

data:  29 out of 125, null probability 0.312
X-squared = 3.3635, df = 1, p-value = 0.03333
alternative hypothesis: true p is less than 0.312
95 percent confidence interval:
 0.0000000 0.3036508
sample estimates:
    p 
0.232 </code></pre>
</div>
<div id="comentarios-sobre-la-salida-de-r-2" class="section level4">
<h4><strong>Comentarios sobre la salida de R</strong></h4>
<div class="alert alert-info">
<p><strong>Importante!</strong> De la anterior salida podemos identificar la siguiente información:</p>
</div>
<p class="comment">
Si no conociéramos los datos de entrada, la salida los proveé, la salida nos dice que <code>data:  29 out of 125</code>, es decir que <span class="math inline">\(n=125\)</span> y que <span class="math inline">\(X=29\)</span>
</p>
<p class="comment">
El p-value es <span class="math inline">\(0.03333\)</span>.
</p>
<p class="comment">
La información de la salida dice que <code>true p is less than 0.312</code>. Entonces <span class="math inline">\(p_0\)</span>, es <span class="math inline">\(0.312\)</span>. Por tanto las hipótesis respectivas fueron: <span class="math display">\[H_0:p = 0.312\]</span> <span class="math display">\[H_a:p &lt; 0.312\]</span>
</p>
<p class="comment">
La significancia es del 5 %, es decir <span class="math inline">\(\alpha = 0.05\)</span>
</p>
<p class="comment">
El valor de p, estimado a traves de <span class="math inline">\(\hat{p}\)</span>, es <span class="math inline">\(p = 0.208\)</span>
</p>
</div>
<div id="decision-y-conclusion" class="section level4">
<h4><strong>Decisión y Conclusión</strong></h4>
</div>
<div id="decision-como-el-p-value-es-menor-que-alpha-es-decir-0.03333-0.05.-la-decision-es-rechazar-la-hipotesis-nula-h_0." class="section level4">
<h4><strong>Decisión:</strong> Como el “p-value” es menor que <span class="math inline">\(\alpha\)</span>, es decir <span class="math inline">\(0.03333 &lt; 0.05\)</span>. La decisión es rechazar la hipotesis nula <span class="math inline">\(H_0\)</span>.</h4>
</div>
<div id="conclusion-en-santa-barbara-california-la-proporcion-de-jovenes-adultos-que-viven-con-sus-padres-es-menor-a-la-proporcion-a-nivel-nacional." class="section level4">
<h4><strong>Conclusión:</strong> En Santa Barbara, California la proporción de jovenes adultos que viven con sus padres es menor a la proporción a nivel nacional.</h4>
</div>
</div>
</div>
<div id="ejercicios-de-repaso" class="section level2">
<h2>Ejercicios de repaso</h2>
<div id="los-investigadores-desean-probar-la-eficacia-de-un-programa-destinado-a-reducir-la-duracion-del-parto-en-el-parto.-el-tiempo-de-trabajo-promedio-aceptado-en-el-nacimiento-de-un-primer-hijo-es-de-15.3-horas.-la-duracion-media-de-los-trabajos-de-13-madres-primerizas-en-un-programa-piloto-fue-de-88-horas.-suponga-que-la-desviacion-estandar-poblacional-es-conocida-e-igual-a-3.1-horas.-suponiendo-una-distribucion-normal-de-los-tiempos-de-trabajo-de-parto-evalue-al-nivel-de-10-de-la-prueba-de-significancia-si-el-tiempo-de-parto-promedio-para-todas-las-mujeres-que-siguen-este-programa-es-menos-de-15.3-horas." class="section level4">
<h4>1. Los investigadores desean probar la eficacia de un programa destinado a reducir la duración del parto en el parto. El tiempo de trabajo promedio aceptado en el nacimiento de un primer hijo es de 15.3 horas. La duración media de los trabajos de 13 madres primerizas en un programa piloto fue de 8,8 horas. Suponga que la desviación estándar poblacional es conocida e igual a 3.1 horas. Suponiendo una distribución normal de los tiempos de trabajo de parto, evalúe al nivel de 10 % de la prueba de significancia si el tiempo de parto promedio para todas las mujeres que siguen este programa es menos de 15.3 horas.</h4>
</div>
<div id="el-precio-de-una-raqueta-de-tenis-popular-en-una-cadena-de-tiendas-nacional-es-de-179.-juan-compro-cinco-de-la-misma-raqueta-en-un-sitio-de-subastas-en-linea-por-los-siguientes-precios" class="section level4">
<h4>2. El precio de una raqueta de tenis popular en una cadena de tiendas nacional es de $ 179. Juan compró cinco de la misma raqueta en un sitio de subastas en línea por los siguientes precios:</h4>
</div>
<div id="section-5" class="section level4">
<h4>155, 179, 175, 175, 161, 145, 151</h4>
</div>
<div id="suponiendo-que-los-precios-de-subasta-de-las-raquetas-se-distribuyen-normalmente-determine-si-hay-suficiente-evidencia-en-la-muestra-al-nivel-de-significancia-del-5-para-concluir-que-el-precio-promedio-de-la-raqueta-es-menor-a-179-si-se-compra-en-una-subasta-en-linea." class="section level4">
<h4>Suponiendo que los precios de subasta de las raquetas se distribuyen normalmente, determine si hay suficiente evidencia en la muestra, al nivel de significancia del 5%, para concluir que el precio promedio de la raqueta es menor a $ 179 si se compra en una subasta en línea.</h4>
</div>
<div id="en-el-pasado-la-duracion-promedio-de-una-llamada-telefonica-saliente-desde-una-oficina-comercial-ha-sido-de-143-segundos.-un-gerente-desea-verificar-si-ese-promedio-ha-disminuido-despues-de-la-introduccion-de-los-cambios-de-politica.-una-muestra-de-100-llamadas-telefonicas-produjo-una-media-de-133-segundos-con-una-desviacion-estandar-de-35-segundos.-realice-la-prueba-pertinente-al-nivel-de-significancia-del-1." class="section level4">
<h4>3. En el pasado, la duración promedio de una llamada telefónica saliente desde una oficina comercial ha sido de 143 segundos. Un gerente desea verificar si ese promedio ha disminuido después de la introducción de los cambios de política. Una muestra de 100 llamadas telefónicas produjo una media de 133 segundos, con una desviación estándar de 35 segundos. Realice la prueba pertinente al nivel de significancia del 1%.</h4>
</div>
<div id="el-tamano-promedio-del-hogar-en-una-region-determinada-hace-varios-anos-era-3.14-personas.-un-sociologo-desea-probar-con-un-nivel-de-significacion-del-5-si-ahora-es-diferente.-realice-la-prueba-con-la-informacion-recopilada-por-el-sociologo-en-una-muestra-aleatoria-de-75-hogares-el-tamano-promedio-fue-de-2.98-personas-con-una-desviacion-estandar-de-muestra-de-0.82-personas." class="section level4">
<h4>4. El tamaño promedio del hogar en una región determinada hace varios años era 3.14 personas. Un sociólogo desea probar, con un nivel de significación del 5%, si ahora es diferente. Realice la prueba con la información recopilada por el sociólogo: en una muestra aleatoria de 75 hogares, el tamaño promedio fue de 2.98 personas, con una desviación estándar de muestra de 0.82 personas.</h4>
</div>
<div id="hace-dos-anos-el-72-de-los-hogares-de-un-determinado-condado-participaban-regularmente-en-el-reciclaje-de-los-desechos-domesticos.-el-gobierno-del-condado-desea-investigar-si-esa-proporcion-ha-aumentado-despues-de-una-campana-intensiva-para-promover-el-reciclaje.-en-una-encuesta-de-900-hogares-674-dijeron-participar-regularmente-en-el-reciclaje.-realice-la-prueba-pertinente-al-nivel-de-significancia-del-10-." class="section level4">
<h4>5. Hace dos años, el 72 % de los hogares de un determinado condado participaban regularmente en el reciclaje de los desechos domésticos. El gobierno del condado desea investigar si esa proporción ha aumentado después de una campaña intensiva para promover el reciclaje. En una encuesta de 900 hogares, 674 dijeron participar regularmente en el reciclaje. Realice la prueba pertinente al nivel de significancia del 10 %.</h4>
</div>
<div id="el-gobierno-de-un-pais-en-particular-informa-que-su-tasa-de-alfabetizacion-es-del-52-.-una-organizacion-no-gubernamental-cree-que-es-menos.-la-organizacion-toma-una-muestra-aleatoria-de-600-habitantes-y-obtiene-una-tasa-de-alfabetizacion-del-42-.-realice-la-prueba-pertinente-al-0.05-de-significancia." class="section level4">
<h4>6. El gobierno de un país en particular informa que su tasa de alfabetización es del 52 %. Una organización no gubernamental cree que es menos. La organización toma una muestra aleatoria de 600 habitantes y obtiene una tasa de alfabetización del 42 %. Realice la prueba pertinente al 0.05 de significancia.</h4>
<div class="figure">
<img src="blanco.png" />

</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
